/*
 Navicat Premium Data Transfer

 Source Server         : xampp mysql
 Source Server Type    : MySQL
 Source Server Version : 100408
 Source Host           : localhost:3306
 Source Schema         : matara

 Target Server Type    : MySQL
 Target Server Version : 100408
 File Encoding         : 65001

 Date: 26/09/2021 01:59:03
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for food
-- ----------------------------
DROP TABLE IF EXISTS `food`;
CREATE TABLE `food`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `region` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1379 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of food
-- ----------------------------
INSERT INTO `food` VALUES (1, 'Ayam Tangkap', 'Aceh');
INSERT INTO `food` VALUES (2, 'Bada Reuteuk', 'Aceh');
INSERT INTO `food` VALUES (3, 'Boh Puniaram', 'Aceh');
INSERT INTO `food` VALUES (4, 'Dalca', 'Aceh');
INSERT INTO `food` VALUES (5, 'Doidoi', 'Aceh');
INSERT INTO `food` VALUES (6, 'Eungkot Paya', 'Aceh');
INSERT INTO `food` VALUES (7, 'Gule Rampoe', 'Aceh');
INSERT INTO `food` VALUES (8, 'Kanji Rumbi', 'Aceh');
INSERT INTO `food` VALUES (9, 'Karah', 'Aceh');
INSERT INTO `food` VALUES (10, 'Keumamah', 'Aceh');
INSERT INTO `food` VALUES (11, 'Kuwah Boh Eungkot', 'Aceh');
INSERT INTO `food` VALUES (12, 'Kuwah Eungkot Rambeue', 'Aceh');
INSERT INTO `food` VALUES (13, 'Kuwah Eungkot Yee', 'Aceh');
INSERT INTO `food` VALUES (14, 'Kuwah Itek', 'Aceh');
INSERT INTO `food` VALUES (15, 'Kuwah Manok', 'Aceh');
INSERT INTO `food` VALUES (16, 'Kuwah Pliek U', 'Aceh');
INSERT INTO `food` VALUES (17, 'Kuwah Sie Kameng', 'Aceh');
INSERT INTO `food` VALUES (18, 'Kuwah Tuhe', 'Aceh');
INSERT INTO `food` VALUES (19, 'Martabak Aceh', 'Aceh');
INSERT INTO `food` VALUES (20, 'Masak Puteh', 'Aceh');
INSERT INTO `food` VALUES (21, 'Masam Keu\'eueng', 'Aceh');
INSERT INTO `food` VALUES (22, 'Meuseukat', 'Aceh');
INSERT INTO `food` VALUES (23, 'Mie Aceh', 'Aceh');
INSERT INTO `food` VALUES (24, 'Nasi Gurih', 'Aceh');
INSERT INTO `food` VALUES (25, 'Payeh', 'Aceh');
INSERT INTO `food` VALUES (26, 'Peukasam Drien', 'Aceh');
INSERT INTO `food` VALUES (27, 'Peunajoh Tho', 'Aceh');
INSERT INTO `food` VALUES (28, 'Ruti Cane', 'Aceh');
INSERT INTO `food` VALUES (29, 'Ruti Jala', 'Aceh');
INSERT INTO `food` VALUES (30, 'Sambai Asam Udeueng', 'Aceh');
INSERT INTO `food` VALUES (31, 'Sambai On Peugaga', 'Aceh');
INSERT INTO `food` VALUES (32, 'Sate Matang', 'Aceh');
INSERT INTO `food` VALUES (33, 'Sie Reuboh', 'Aceh');
INSERT INTO `food` VALUES (34, 'Sop Sumsum', 'Aceh');
INSERT INTO `food` VALUES (35, 'Timphan', 'Aceh');
INSERT INTO `food` VALUES (36, 'Wajeb', 'Aceh');
INSERT INTO `food` VALUES (37, 'Lompong Sagu', 'Aceh');
INSERT INTO `food` VALUES (38, 'Masam Jing', 'Aceh');
INSERT INTO `food` VALUES (39, 'Depik Dedah', 'Aceh');
INSERT INTO `food` VALUES (40, 'Pengat', 'Aceh');
INSERT INTO `food` VALUES (41, 'Angsle', 'Sumatra Utara');
INSERT INTO `food` VALUES (42, 'Arsik', 'Sumatra Utara');
INSERT INTO `food` VALUES (43, 'Babi Panggang Karo', 'Sumatra Utara');
INSERT INTO `food` VALUES (44, 'Bika Ambon', 'Sumatra Utara');
INSERT INTO `food` VALUES (45, 'Bolu Gulung', 'Sumatra Utara');
INSERT INTO `food` VALUES (46, 'Bubur Melayu', 'Sumatra Utara');
INSERT INTO `food` VALUES (47, 'Bulung Gadung', 'Sumatra Utara');
INSERT INTO `food` VALUES (48, 'Cimpa', 'Sumatra Utara');
INSERT INTO `food` VALUES (49, 'Cipera', 'Sumatra Utara');
INSERT INTO `food` VALUES (50, 'Dalini Horbo', 'Sumatra Utara');
INSERT INTO `food` VALUES (51, 'Halua', 'Sumatra Utara');
INSERT INTO `food` VALUES (52, 'Ikan Holat', 'Sumatra Utara');
INSERT INTO `food` VALUES (53, 'Ikan Sale', 'Sumatra Utara');
INSERT INTO `food` VALUES (54, 'Kidu-Kidu', 'Sumatra Utara');
INSERT INTO `food` VALUES (55, 'Kwetiau', 'Sumatra Utara');
INSERT INTO `food` VALUES (56, 'Lapis Legit', 'Sumatra Utara');
INSERT INTO `food` VALUES (57, 'Lappet Gadong', 'Sumatra Utara');
INSERT INTO `food` VALUES (58, 'Lappet Pohul-pohul', 'Sumatra Utara');
INSERT INTO `food` VALUES (59, 'Lappet', 'Sumatra Utara');
INSERT INTO `food` VALUES (60, 'Lemang', 'Sumatra Utara');
INSERT INTO `food` VALUES (61, 'Lomok-Lomok', 'Sumatra Utara');
INSERT INTO `food` VALUES (62, 'Mie Gomak', 'Sumatra Utara');
INSERT INTO `food` VALUES (63, 'Mutiara Bagan Siapi-api', 'Sumatra Utara');
INSERT INTO `food` VALUES (64, 'Nanidugu', 'Sumatra Utara');
INSERT INTO `food` VALUES (65, 'Naniura', 'Sumatra Utara');
INSERT INTO `food` VALUES (66, 'Ombus-Ombus', 'Sumatra Utara');
INSERT INTO `food` VALUES (67, 'Pangsit', 'Sumatra Utara');
INSERT INTO `food` VALUES (68, 'Pisang Molen', 'Sumatra Utara');
INSERT INTO `food` VALUES (69, 'Pok pia', 'Sumatra Utara');
INSERT INTO `food` VALUES (70, 'Roti Ketawa', 'Sumatra Utara');
INSERT INTO `food` VALUES (71, 'Roti Kosong', 'Sumatra Utara');
INSERT INTO `food` VALUES (72, 'Saksang', 'Sumatra Utara');
INSERT INTO `food` VALUES (73, 'Sambal Rias', 'Sumatra Utara');
INSERT INTO `food` VALUES (74, 'Sambal Tuk Tuk', 'Sumatra Utara');
INSERT INTO `food` VALUES (75, 'Sambel Hebi', 'Sumatra Utara');
INSERT INTO `food` VALUES (76, 'Sangsang', 'Sumatra Utara');
INSERT INTO `food` VALUES (77, 'Soto Medan', 'Sumatra Utara');
INSERT INTO `food` VALUES (78, 'Tanggotanggo', 'Sumatra Utara');
INSERT INTO `food` VALUES (79, 'Terites', 'Sumatra Utara');
INSERT INTO `food` VALUES (80, 'Tipa-tipa', 'Sumatra Utara');
INSERT INTO `food` VALUES (81, 'Tok-tok', 'Sumatra Utara');
INSERT INTO `food` VALUES (82, 'Uyen', 'Sumatra Utara');
INSERT INTO `food` VALUES (83, 'Panggang Geleng', 'Sumatra Utara');
INSERT INTO `food` VALUES (84, 'Sambam Lauk', 'Sumatra Utara');
INSERT INTO `food` VALUES (85, 'Tumbang Goreng', 'Sumatra Utara');
INSERT INTO `food` VALUES (86, 'Gulei Hiu', 'Sumatra Utara');
INSERT INTO `food` VALUES (87, 'Ale-ale', 'Sumatra Barat');
INSERT INTO `food` VALUES (88, 'Asam pedas', 'Sumatra Barat');
INSERT INTO `food` VALUES (89, 'Ayam pop', 'Sumatra Barat');
INSERT INTO `food` VALUES (90, 'Balado bawal', 'Sumatra Barat');
INSERT INTO `food` VALUES (91, 'Belut goreng', 'Sumatra Barat');
INSERT INTO `food` VALUES (92, 'Beras rendang', 'Sumatra Barat');
INSERT INTO `food` VALUES (93, 'Bika Siana', 'Sumatra Barat');
INSERT INTO `food` VALUES (94, 'Bika', 'Sumatra Barat');
INSERT INTO `food` VALUES (95, 'Bubur Kampiun', 'Sumatra Barat');
INSERT INTO `food` VALUES (96, 'Cindua', 'Sumatra Barat');
INSERT INTO `food` VALUES (97, 'Cokelat rendang', 'Sumatra Barat');
INSERT INTO `food` VALUES (98, 'Dadiah', 'Sumatra Barat');
INSERT INTO `food` VALUES (99, 'Dakak-dakak', 'Sumatra Barat');
INSERT INTO `food` VALUES (100, 'Dendeng balado', 'Sumatra Barat');
INSERT INTO `food` VALUES (101, 'Dendeng batokok', 'Sumatra Barat');
INSERT INTO `food` VALUES (102, 'Gajebo', 'Sumatra Barat');
INSERT INTO `food` VALUES (103, 'Galamai', 'Sumatra Barat');
INSERT INTO `food` VALUES (104, 'Gulai banak', 'Sumatra Barat');
INSERT INTO `food` VALUES (105, 'Gulai cubadak', 'Sumatra Barat');
INSERT INTO `food` VALUES (106, 'Gulai itiak', 'Sumatra Barat');
INSERT INTO `food` VALUES (107, 'Gulai kambiang', 'Sumatra Barat');
INSERT INTO `food` VALUES (108, 'Gulai kemumu', 'Sumatra Barat');
INSERT INTO `food` VALUES (109, 'Gulai paku', 'Sumatra Barat');
INSERT INTO `food` VALUES (110, 'Gulai pucuak ubi', 'Sumatra Barat');
INSERT INTO `food` VALUES (111, 'Gulai tambusu', 'Sumatra Barat');
INSERT INTO `food` VALUES (112, 'Gulai toco', 'Sumatra Barat');
INSERT INTO `food` VALUES (113, 'Gulai', 'Sumatra Barat');
INSERT INTO `food` VALUES (114, 'Ikan baka', 'Sumatra Barat');
INSERT INTO `food` VALUES (115, 'Ikan balado', 'Sumatra Barat');
INSERT INTO `food` VALUES (116, 'Kalio', 'Sumatra Barat');
INSERT INTO `food` VALUES (117, 'Karak kaliang', 'Sumatra Barat');
INSERT INTO `food` VALUES (118, 'Keripik sanjai', 'Sumatra Barat');
INSERT INTO `food` VALUES (119, 'Kerupuk jangek', 'Sumatra Barat');
INSERT INTO `food` VALUES (120, 'Kerupuk jariang', 'Sumatra Barat');
INSERT INTO `food` VALUES (121, 'Ketan durian', 'Sumatra Barat');
INSERT INTO `food` VALUES (122, 'Ketan sarikaya', 'Sumatra Barat');
INSERT INTO `food` VALUES (123, 'Kipang', 'Sumatra Barat');
INSERT INTO `food` VALUES (124, 'Lamang tapai', 'Sumatra Barat');
INSERT INTO `food` VALUES (125, 'Lapek bugih', 'Sumatra Barat');
INSERT INTO `food` VALUES (126, 'Lamang', 'Sumatra Barat');
INSERT INTO `food` VALUES (127, 'Lontong pitalah', 'Sumatra Barat');
INSERT INTO `food` VALUES (128, 'Martabak Mesir', 'Sumatra Barat');
INSERT INTO `food` VALUES (129, 'Nasi Kapau', 'Sumatra Barat');
INSERT INTO `food` VALUES (130, 'Palai bada', 'Sumatra Barat');
INSERT INTO `food` VALUES (131, 'Palai rinuak', 'Sumatra Barat');
INSERT INTO `food` VALUES (132, 'Pangek masin', 'Sumatra Barat');
INSERT INTO `food` VALUES (133, 'Pensi', 'Sumatra Barat');
INSERT INTO `food` VALUES (134, 'Pergedel jagung', 'Sumatra Barat');
INSERT INTO `food` VALUES (135, 'Pinyaram', 'Sumatra Barat');
INSERT INTO `food` VALUES (136, 'Rakik maco', 'Sumatra Barat');
INSERT INTO `food` VALUES (137, 'Rendang', 'Sumatra Barat');
INSERT INTO `food` VALUES (138, 'Sagon bakar', 'Sumatra Barat');
INSERT INTO `food` VALUES (139, 'Sambalado tanak', 'Sumatra Barat');
INSERT INTO `food` VALUES (140, 'Sarang balam', 'Sumatra Barat');
INSERT INTO `food` VALUES (141, 'Sate Padang', 'Sumatra Barat');
INSERT INTO `food` VALUES (142, 'Sate Pariaman', 'Sumatra Barat');
INSERT INTO `food` VALUES (143, 'Sarabi', 'Sumatra Barat');
INSERT INTO `food` VALUES (144, 'Soto Padang', 'Sumatra Barat');
INSERT INTO `food` VALUES (145, 'Tolu-tolu', 'Sumatra Barat');
INSERT INTO `food` VALUES (146, 'Wajik', 'Sumatra Barat');
INSERT INTO `food` VALUES (147, 'Daging masak hitam', 'Jambi');
INSERT INTO `food` VALUES (148, 'Gelamai Perentak', 'Jambi');
INSERT INTO `food` VALUES (149, 'Gulai belut', 'Jambi');
INSERT INTO `food` VALUES (150, 'Gulai ikan semah', 'Jambi');
INSERT INTO `food` VALUES (151, 'Gulai Tekuyung', 'Jambi');
INSERT INTO `food` VALUES (152, 'Gulai tepek ikan', 'Jambi');
INSERT INTO `food` VALUES (153, 'Gulai terjun daging', 'Jambi');
INSERT INTO `food` VALUES (154, 'Kerutup ikan', 'Jambi');
INSERT INTO `food` VALUES (155, 'Lemang', 'Jambi');
INSERT INTO `food` VALUES (156, 'Nasi gemuk', 'Jambi');
INSERT INTO `food` VALUES (157, 'Nasi lemak', 'Jambi');
INSERT INTO `food` VALUES (158, 'Pempek sambal', 'Jambi');
INSERT INTO `food` VALUES (159, 'Sambal Salabance', 'Jambi');
INSERT INTO `food` VALUES (160, 'Tempoyak', 'Jambi');
INSERT INTO `food` VALUES (161, 'Godok-godok', 'Bengkulu');
INSERT INTO `food` VALUES (162, 'Kelicuk', 'Bengkulu');
INSERT INTO `food` VALUES (163, 'Lema', 'Bengkulu');
INSERT INTO `food` VALUES (164, 'Pendap', 'Bengkulu');
INSERT INTO `food` VALUES (165, 'Tempoyak', 'Bengkulu');
INSERT INTO `food` VALUES (166, 'Tapai ketan', 'Bengkulu');
INSERT INTO `food` VALUES (167, 'Ayam Geprek', 'Bengkulu');
INSERT INTO `food` VALUES (168, 'Ayam Bakar', 'Bengkulu');
INSERT INTO `food` VALUES (169, 'Bakso Beranak', 'Bengkulu');
INSERT INTO `food` VALUES (170, 'Pucuk ubi', 'Bengkulu');
INSERT INTO `food` VALUES (171, 'Lempuk Durian', 'Bengkulu');
INSERT INTO `food` VALUES (172, 'Dodol Durian', 'Bengkulu');
INSERT INTO `food` VALUES (173, 'Dadar Gulung', 'Bengkulu');
INSERT INTO `food` VALUES (174, 'Brengkes Tempoyak', 'Sumatra Selatan');
INSERT INTO `food` VALUES (175, 'Brengkes Udang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (176, 'Brengkes', 'Sumatra Selatan');
INSERT INTO `food` VALUES (177, 'Bolu Kojo', 'Sumatra Selatan');
INSERT INTO `food` VALUES (178, 'Bolu Lapis', 'Sumatra Selatan');
INSERT INTO `food` VALUES (179, 'Burgo', 'Sumatra Selatan');
INSERT INTO `food` VALUES (180, 'Gangan Udang satang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (181, 'Gulai Malbi', 'Sumatra Selatan');
INSERT INTO `food` VALUES (182, 'Gulai Tempoyak', 'Sumatra Selatan');
INSERT INTO `food` VALUES (183, 'Ikan Pais', 'Sumatra Selatan');
INSERT INTO `food` VALUES (184, 'Ikan Pakasam', 'Sumatra Selatan');
INSERT INTO `food` VALUES (185, 'Ikan Peda', 'Sumatra Selatan');
INSERT INTO `food` VALUES (186, 'Ikan Rusip', 'Sumatra Selatan');
INSERT INTO `food` VALUES (187, 'Ikan Salai', 'Sumatra Selatan');
INSERT INTO `food` VALUES (188, 'Kemplang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (189, 'Kluntup', 'Sumatra Selatan');
INSERT INTO `food` VALUES (190, 'Kue Bangket', 'Sumatra Selatan');
INSERT INTO `food` VALUES (191, 'Kue Satu', 'Sumatra Selatan');
INSERT INTO `food` VALUES (192, 'Kue Lapan Jam', 'Sumatra Selatan');
INSERT INTO `food` VALUES (193, 'Kue Maksuba', 'Sumatra Selatan');
INSERT INTO `food` VALUES (194, 'Laksa', 'Sumatra Selatan');
INSERT INTO `food` VALUES (195, 'Mie Celor', 'Sumatra Selatan');
INSERT INTO `food` VALUES (196, 'Model', 'Sumatra Selatan');
INSERT INTO `food` VALUES (197, 'Nasi Lemak', 'Sumatra Selatan');
INSERT INTO `food` VALUES (198, 'Nasi Minyak', 'Sumatra Selatan');
INSERT INTO `food` VALUES (199, 'Nasi Samin', 'Sumatra Selatan');
INSERT INTO `food` VALUES (200, 'Otak-otak', 'Sumatra Selatan');
INSERT INTO `food` VALUES (201, 'Pempek Adaan', 'Sumatra Selatan');
INSERT INTO `food` VALUES (202, 'Pempek Kapal Selam', 'Sumatra Selatan');
INSERT INTO `food` VALUES (203, 'Pempek Keriting', 'Sumatra Selatan');
INSERT INTO `food` VALUES (204, 'Pempek Kulit', 'Sumatra Selatan');
INSERT INTO `food` VALUES (205, 'Pempek Lenjer', 'Sumatra Selatan');
INSERT INTO `food` VALUES (206, 'Pempek Lenggang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (207, 'Pempek Panggang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (208, 'Pempek Pistel', 'Sumatra Selatan');
INSERT INTO `food` VALUES (209, 'Pempek Telor', 'Sumatra Selatan');
INSERT INTO `food` VALUES (210, 'Pempek Isi Udang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (211, 'Pindang Daging/Tulang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (212, 'Pindang Ayam', 'Sumatra Selatan');
INSERT INTO `food` VALUES (213, 'Pindang Ikan patin', 'Sumatra Selatan');
INSERT INTO `food` VALUES (214, 'Pindang Salai', 'Sumatra Selatan');
INSERT INTO `food` VALUES (215, 'Pindang maranjat', 'Sumatra Selatan');
INSERT INTO `food` VALUES (216, 'Pindang pegagan', 'Sumatra Selatan');
INSERT INTO `food` VALUES (217, 'Rujak Mie', 'Sumatra Selatan');
INSERT INTO `food` VALUES (218, 'pepes tempoyak', 'Sumatra Selatan');
INSERT INTO `food` VALUES (219, 'pepes asam belimbing', 'Sumatra Selatan');
INSERT INTO `food` VALUES (220, 'Sambal Goreng Campur', 'Sumatra Selatan');
INSERT INTO `food` VALUES (221, 'Sambal Kemang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (222, 'Sambal Kweni', 'Sumatra Selatan');
INSERT INTO `food` VALUES (223, 'Sambal Lingkung', 'Sumatra Selatan');
INSERT INTO `food` VALUES (224, 'Sambal Mbacang', 'Sumatra Selatan');
INSERT INTO `food` VALUES (225, 'Sambal jokjok', 'Sumatra Selatan');
INSERT INTO `food` VALUES (226, 'Sayur Kasam', 'Sumatra Selatan');
INSERT INTO `food` VALUES (227, 'Tekwan', 'Sumatra Selatan');
INSERT INTO `food` VALUES (228, 'Air Mata Pengantin', 'Riau');
INSERT INTO `food` VALUES (229, 'Bangket Durian', 'Riau');
INSERT INTO `food` VALUES (230, 'Bolu Kemojo/Kamboja', 'Riau');
INSERT INTO `food` VALUES (231, 'Bolu Berendam', 'Riau');
INSERT INTO `food` VALUES (232, 'Es Laksamana Mengamuk', 'Riau');
INSERT INTO `food` VALUES (233, 'Gendar Ketan Hitam', 'Riau');
INSERT INTO `food` VALUES (234, 'Juice Jagung Manis', 'Riau');
INSERT INTO `food` VALUES (235, 'Juice Tiga Rasa', 'Riau');
INSERT INTO `food` VALUES (236, 'Kluntup', 'Riau');
INSERT INTO `food` VALUES (237, 'Kue 8 Jam', 'Riau');
INSERT INTO `food` VALUES (238, 'Kue Bangket Jeruk Nipis', 'Riau');
INSERT INTO `food` VALUES (239, 'Kue Bawang', 'Riau');
INSERT INTO `food` VALUES (240, 'Lenggang', 'Riau');
INSERT INTO `food` VALUES (241, 'Pais Udang', 'Riau');
INSERT INTO `food` VALUES (242, 'Pindang Jamur', 'Riau');
INSERT INTO `food` VALUES (243, 'Rujak maharaja', 'Riau');
INSERT INTO `food` VALUES (244, 'Sambal Belacan', 'Riau');
INSERT INTO `food` VALUES (245, 'Sambal Goreng Campur', 'Riau');
INSERT INTO `food` VALUES (246, 'Sayur Kasam', 'Riau');
INSERT INTO `food` VALUES (247, 'Asam pedas', 'Kepulauan Riau');
INSERT INTO `food` VALUES (248, 'Asam rujak (Rujak ketam)', 'Kepulauan Riau');
INSERT INTO `food` VALUES (249, 'Bubur pulut hitam', 'Kepulauan Riau');
INSERT INTO `food` VALUES (250, 'Bubur tepung ubi kayu', 'Kepulauan Riau');
INSERT INTO `food` VALUES (251, 'Daun ubi sambal belacan', 'Kepulauan Riau');
INSERT INTO `food` VALUES (252, 'Gobak sagu (Lendot)', 'Kepulauan Riau');
INSERT INTO `food` VALUES (253, 'Gulai Siput', 'Kepulauan Riau');
INSERT INTO `food` VALUES (254, 'Kernas', 'Kepulauan Riau');
INSERT INTO `food` VALUES (255, 'Kerye', 'Kepulauan Riau');
INSERT INTO `food` VALUES (256, 'Laksa', 'Kepulauan Riau');
INSERT INTO `food` VALUES (257, 'Laksa Goreng', 'Kepulauan Riau');
INSERT INTO `food` VALUES (258, 'Lakse', 'Kepulauan Riau');
INSERT INTO `food` VALUES (259, 'Lempeng', 'Kepulauan Riau');
INSERT INTO `food` VALUES (260, 'Lampam', 'Kepulauan Riau');
INSERT INTO `food` VALUES (261, 'Kepurun', 'Kepulauan Riau');
INSERT INTO `food` VALUES (262, 'Gubal', 'Kepulauan Riau');
INSERT INTO `food` VALUES (263, 'Sagu Lemak', 'Kepulauan Riau');
INSERT INTO `food` VALUES (264, 'Sagu lenggang', 'Kepulauan Riau');
INSERT INTO `food` VALUES (265, 'Keripik Sagu Lenggang', 'Kepulauan Riau');
INSERT INTO `food` VALUES (266, 'Keripik Sagu Bakar', 'Kepulauan Riau');
INSERT INTO `food` VALUES (267, 'Kerupuk Cincin', 'Kepulauan Riau');
INSERT INTO `food` VALUES (268, 'Lambok', 'Kepulauan Riau');
INSERT INTO `food` VALUES (269, 'Mie Lendir', 'Kepulauan Riau');
INSERT INTO `food` VALUES (270, 'Mie Tarempa', 'Kepulauan Riau');
INSERT INTO `food` VALUES (271, 'Mie Sagu', 'Kepulauan Riau');
INSERT INTO `food` VALUES (272, 'Mie Siam Kuning', 'Kepulauan Riau');
INSERT INTO `food` VALUES (273, 'Nasi Goreng Kampung', 'Kepulauan Riau');
INSERT INTO `food` VALUES (274, 'Nasi Dagang', 'Kepulauan Riau');
INSERT INTO `food` VALUES (275, 'Nasi Lemak', 'Kepulauan Riau');
INSERT INTO `food` VALUES (276, 'Onde onde ubi kayu', 'Kepulauan Riau');
INSERT INTO `food` VALUES (277, 'Pacri nanas', 'Kepulauan Riau');
INSERT INTO `food` VALUES (278, 'Pulut', 'Kepulauan Riau');
INSERT INTO `food` VALUES (279, 'Roti canai', 'Kepulauan Riau');
INSERT INTO `food` VALUES (280, 'Roti jala', 'Kepulauan Riau');
INSERT INTO `food` VALUES (281, 'Roti kirai', 'Kepulauan Riau');
INSERT INTO `food` VALUES (282, 'Roti prata', 'Kepulauan Riau');
INSERT INTO `food` VALUES (283, 'Sambal mangga', 'Kepulauan Riau');
INSERT INTO `food` VALUES (284, 'Sambal bilis kacang', 'Kepulauan Riau');
INSERT INTO `food` VALUES (285, 'Sambal belacan', 'Kepulauan Riau');
INSERT INTO `food` VALUES (286, 'Sambal lingkong gonggong', 'Kepulauan Riau');
INSERT INTO `food` VALUES (287, 'Sop ikan Batam', 'Kepulauan Riau');
INSERT INTO `food` VALUES (288, 'Sotong masak hitam', 'Kepulauan Riau');
INSERT INTO `food` VALUES (289, 'Siput Gonggong', 'Kepulauan Riau');
INSERT INTO `food` VALUES (290, 'Siput sedot', 'Kepulauan Riau');
INSERT INTO `food` VALUES (291, 'Buak Balak', 'Lampung');
INSERT INTO `food` VALUES (292, 'Buak Lambang Sari', 'Lampung');
INSERT INTO `food` VALUES (293, 'Gelemok', 'Lampung');
INSERT INTO `food` VALUES (294, 'Gulai Balak', 'Lampung');
INSERT INTO `food` VALUES (295, 'Gulai Taboh', 'Lampung');
INSERT INTO `food` VALUES (296, 'Keripik Pisang', 'Lampung');
INSERT INTO `food` VALUES (297, 'Sekubal/Ketan Lapis', 'Lampung');
INSERT INTO `food` VALUES (298, 'Seruwit', 'Lampung');
INSERT INTO `food` VALUES (299, 'Ayam bekakak', 'Banten');
INSERT INTO `food` VALUES (300, 'Apem Putih', 'Banten');
INSERT INTO `food` VALUES (301, 'Cuwer', 'Banten');
INSERT INTO `food` VALUES (302, 'Emping', 'Banten');
INSERT INTO `food` VALUES (303, 'Gemblong', 'Banten');
INSERT INTO `food` VALUES (304, 'Gipang', 'Banten');
INSERT INTO `food` VALUES (305, 'Jojorong', 'Banten');
INSERT INTO `food` VALUES (306, 'Keceprek Melinjo', 'Banten');
INSERT INTO `food` VALUES (307, 'Lemeng', 'Banten');
INSERT INTO `food` VALUES (308, 'Nasi Sumsum', 'Banten');
INSERT INTO `food` VALUES (309, 'Otak-otak', 'Banten');
INSERT INTO `food` VALUES (310, 'Rabeg', 'Banten');
INSERT INTO `food` VALUES (311, 'Sate Bandeng', 'Banten');
INSERT INTO `food` VALUES (312, 'Sate Bebek', 'Banten');
INSERT INTO `food` VALUES (313, 'Semur', 'Banten');
INSERT INTO `food` VALUES (314, 'Taoge Goreng', 'Banten');
INSERT INTO `food` VALUES (315, 'Asinan Jakarta', 'DKI Jakarta');
INSERT INTO `food` VALUES (316, 'Bagane', 'DKI Jakarta');
INSERT INTO `food` VALUES (317, 'Banding Bakar Marunda', 'DKI Jakarta');
INSERT INTO `food` VALUES (318, 'Begana', 'DKI Jakarta');
INSERT INTO `food` VALUES (319, 'Bir Pletok', 'DKI Jakarta');
INSERT INTO `food` VALUES (320, 'Bubur Ayam Betawi', 'DKI Jakarta');
INSERT INTO `food` VALUES (321, 'Capsay Petai', 'DKI Jakarta');
INSERT INTO `food` VALUES (322, 'Dodol Legit', 'DKI Jakarta');
INSERT INTO `food` VALUES (323, 'Emping', 'DKI Jakarta');
INSERT INTO `food` VALUES (324, 'Es Doger', 'DKI Jakarta');
INSERT INTO `food` VALUES (325, 'Es Teler', 'DKI Jakarta');
INSERT INTO `food` VALUES (326, 'Gado-gado', 'DKI Jakarta');
INSERT INTO `food` VALUES (327, 'Geplak', 'DKI Jakarta');
INSERT INTO `food` VALUES (328, 'Kerak Telor', 'DKI Jakarta');
INSERT INTO `food` VALUES (329, 'Ketoprak', 'DKI Jakarta');
INSERT INTO `food` VALUES (330, 'Kimlo', 'DKI Jakarta');
INSERT INTO `food` VALUES (331, 'Kroket', 'DKI Jakarta');
INSERT INTO `food` VALUES (332, 'Kue apem betawi', 'DKI Jakarta');
INSERT INTO `food` VALUES (333, 'Kue Bakar', 'DKI Jakarta');
INSERT INTO `food` VALUES (334, 'Kue jongkong', 'DKI Jakarta');
INSERT INTO `food` VALUES (335, 'Kue Pepe', 'DKI Jakarta');
INSERT INTO `food` VALUES (336, 'Kue Rangi', 'DKI Jakarta');
INSERT INTO `food` VALUES (337, 'Kue unti', 'DKI Jakarta');
INSERT INTO `food` VALUES (338, 'Lontong Sayur Khas Betawi', 'DKI Jakarta');
INSERT INTO `food` VALUES (339, 'Marak', 'DKI Jakarta');
INSERT INTO `food` VALUES (340, 'Nasi Bukhari', 'DKI Jakarta');
INSERT INTO `food` VALUES (341, 'Nasi Goreng Daon Mengkudu', 'DKI Jakarta');
INSERT INTO `food` VALUES (342, 'Nasi Goreng Gila', 'DKI Jakarta');
INSERT INTO `food` VALUES (343, 'Nasi Goreng Kambing', 'DKI Jakarta');
INSERT INTO `food` VALUES (344, 'Nasi Kebuli', 'DKI Jakarta');
INSERT INTO `food` VALUES (345, 'Nasi Uduk', 'DKI Jakarta');
INSERT INTO `food` VALUES (346, 'Onde-onde', 'DKI Jakarta');
INSERT INTO `food` VALUES (347, 'Ongol-Ongol', 'DKI Jakarta');
INSERT INTO `food` VALUES (348, 'Pecak Gurame', 'DKI Jakarta');
INSERT INTO `food` VALUES (349, 'Pelas', 'DKI Jakarta');
INSERT INTO `food` VALUES (350, 'PeSalak', 'DKI Jakarta');
INSERT INTO `food` VALUES (351, 'Pesmo Gurami', 'DKI Jakarta');
INSERT INTO `food` VALUES (352, 'Pindang Serani', 'DKI Jakarta');
INSERT INTO `food` VALUES (353, 'Risoles', 'DKI Jakarta');
INSERT INTO `food` VALUES (354, 'Roti Buaya', 'DKI Jakarta');
INSERT INTO `food` VALUES (355, 'Rujak Bebeg', 'DKI Jakarta');
INSERT INTO `food` VALUES (356, 'Sayur Bebanci', 'DKI Jakarta');
INSERT INTO `food` VALUES (357, 'Sayur Besan', 'DKI Jakarta');
INSERT INTO `food` VALUES (358, 'Sayur Gabus Pucungcak', 'DKI Jakarta');
INSERT INTO `food` VALUES (359, 'Semur Betawi', 'DKI Jakarta');
INSERT INTO `food` VALUES (360, 'Semur Jengkol', 'DKI Jakarta');
INSERT INTO `food` VALUES (361, 'Semur Terung Betawi', 'DKI Jakarta');
INSERT INTO `food` VALUES (362, 'Serondeng', 'DKI Jakarta');
INSERT INTO `food` VALUES (363, 'Sop Kaki Kambing', 'DKI Jakarta');
INSERT INTO `food` VALUES (364, 'Soto Betawi', 'DKI Jakarta');
INSERT INTO `food` VALUES (365, 'Soto Mi', 'DKI Jakarta');
INSERT INTO `food` VALUES (366, 'Talam Udang', 'DKI Jakarta');
INSERT INTO `food` VALUES (367, 'Taoge Goreng', 'DKI Jakarta');
INSERT INTO `food` VALUES (368, 'Telubuk Sayur', 'DKI Jakarta');
INSERT INTO `food` VALUES (369, 'Ambokueh', 'Jawa Barat');
INSERT INTO `food` VALUES (370, 'Bajigur', 'Jawa Barat');
INSERT INTO `food` VALUES (371, 'Bakso Kocok', 'Jawa Barat');
INSERT INTO `food` VALUES (372, 'Bala-bala', 'Jawa Barat');
INSERT INTO `food` VALUES (373, 'Bandrek', 'Jawa Barat');
INSERT INTO `food` VALUES (374, 'Batagor', 'Jawa Barat');
INSERT INTO `food` VALUES (375, 'Brownies Kukus', 'Jawa Barat');
INSERT INTO `food` VALUES (376, 'Cireng', 'Jawa Barat');
INSERT INTO `food` VALUES (377, 'Cokelat Suzanna', 'Jawa Barat');
INSERT INTO `food` VALUES (378, 'Colenak (Tape bakar saus kelapa gula merah)', 'Jawa Barat');
INSERT INTO `food` VALUES (379, 'Combro', 'Jawa Barat');
INSERT INTO `food` VALUES (380, 'Gehu', 'Jawa Barat');
INSERT INTO `food` VALUES (381, 'Gepuk', 'Jawa Barat');
INSERT INTO `food` VALUES (382, 'Gurame Bakar', 'Jawa Barat');
INSERT INTO `food` VALUES (383, 'Jagung Bakar', 'Jawa Barat');
INSERT INTO `food` VALUES (384, 'Karedok', 'Jawa Barat');
INSERT INTO `food` VALUES (385, 'Kolontong', 'Jawa Barat');
INSERT INTO `food` VALUES (386, 'Kue Sus', 'Jawa Barat');
INSERT INTO `food` VALUES (387, 'Lotek', 'Jawa Barat');
INSERT INTO `food` VALUES (388, 'Mi Kocok', 'Jawa Barat');
INSERT INTO `food` VALUES (389, 'Misro', 'Jawa Barat');
INSERT INTO `food` VALUES (390, 'Nasi Timbel', 'Jawa Barat');
INSERT INTO `food` VALUES (391, 'Pepes Ikan Mas', 'Jawa Barat');
INSERT INTO `food` VALUES (392, 'Pepes Jamur', 'Jawa Barat');
INSERT INTO `food` VALUES (393, 'Perkedel Bondon', 'Jawa Barat');
INSERT INTO `food` VALUES (394, 'Peuyeum', 'Jawa Barat');
INSERT INTO `food` VALUES (395, 'Pisang Molen', 'Jawa Barat');
INSERT INTO `food` VALUES (396, 'Sakoteng', 'Jawa Barat');
INSERT INTO `food` VALUES (397, 'Sayur Asam', 'Jawa Barat');
INSERT INTO `food` VALUES (398, 'Seblak', 'Jawa Barat');
INSERT INTO `food` VALUES (399, 'Serabi Oncom', 'Jawa Barat');
INSERT INTO `food` VALUES (400, 'Serabi', 'Jawa Barat');
INSERT INTO `food` VALUES (401, 'Soto Bandung', 'Jawa Barat');
INSERT INTO `food` VALUES (402, 'Ubi Bakar', 'Jawa Barat');
INSERT INTO `food` VALUES (403, 'Kue Cubit', 'Jawa Barat');
INSERT INTO `food` VALUES (404, 'Tahu bulat', 'Jawa Barat');
INSERT INTO `food` VALUES (405, 'Tahu Sumedang', 'Jawa Barat');
INSERT INTO `food` VALUES (406, 'Asinan Sukasari', 'Jawa Barat');
INSERT INTO `food` VALUES (407, 'Sambel Oncom', 'Jawa Barat');
INSERT INTO `food` VALUES (408, 'Sayur Asam Kacang Merah', 'Jawa Barat');
INSERT INTO `food` VALUES (409, 'Tauco Cianjur', 'Jawa Barat');
INSERT INTO `food` VALUES (410, 'Toge Tauco (Geco)', 'Jawa Barat');
INSERT INTO `food` VALUES (411, 'Manisan Cianjur', 'Jawa Barat');
INSERT INTO `food` VALUES (412, 'Kupat Tahu', 'Jawa Barat');
INSERT INTO `food` VALUES (413, 'Nasi Tutug Oncom', 'Jawa Barat');
INSERT INTO `food` VALUES (414, 'Soto Ayam Tasik', 'Jawa Barat');
INSERT INTO `food` VALUES (415, 'Bakmi Babat Kremes', 'Jawa Barat');
INSERT INTO `food` VALUES (416, 'Tahu Bulat', 'Jawa Barat');
INSERT INTO `food` VALUES (417, 'Gula Cakar', 'Jawa Barat');
INSERT INTO `food` VALUES (418, 'Kupat Tahu', 'Jawa Barat');
INSERT INTO `food` VALUES (419, 'Mangga Gedung Gincu', 'Jawa Barat');
INSERT INTO `food` VALUES (420, 'Pindang Tetel', 'Jawa Barat');
INSERT INTO `food` VALUES (421, 'Golono', 'Jawa Barat');
INSERT INTO `food` VALUES (422, 'Hucap', 'Jawa Barat');
INSERT INTO `food` VALUES (423, 'Rujak Kangkung', 'Jawa Barat');
INSERT INTO `food` VALUES (424, 'Kwecang', 'Jawa Barat');
INSERT INTO `food` VALUES (425, 'Pepes Jamur Kayu', 'Jawa Barat');
INSERT INTO `food` VALUES (426, 'Peuyeum Ketan', 'Jawa Barat');
INSERT INTO `food` VALUES (427, 'Sangu Kasreng', 'Jawa Barat');
INSERT INTO `food` VALUES (428, 'Sop Tutut', 'Jawa Barat');
INSERT INTO `food` VALUES (429, 'Tahu Kopeci', 'Jawa Barat');
INSERT INTO `food` VALUES (430, 'Dodol Garut', 'Jawa Barat');
INSERT INTO `food` VALUES (431, 'Dorokdok', 'Jawa Barat');
INSERT INTO `food` VALUES (432, 'Ladu', 'Jawa Barat');
INSERT INTO `food` VALUES (433, 'Docang', 'Jawa Barat');
INSERT INTO `food` VALUES (434, 'Empal Asem', 'Jawa Barat');
INSERT INTO `food` VALUES (435, 'Empal Gentong', 'Jawa Barat');
INSERT INTO `food` VALUES (436, 'Kerupuk Mlarat', 'Jawa Barat');
INSERT INTO `food` VALUES (437, 'Mi Koclok', 'Jawa Barat');
INSERT INTO `food` VALUES (438, 'Sega Jamblang', 'Jawa Barat');
INSERT INTO `food` VALUES (439, 'Sega Lengko', 'Jawa Barat');
INSERT INTO `food` VALUES (440, 'Soto Cirebon', 'Jawa Barat');
INSERT INTO `food` VALUES (441, 'Tahu Gejrot', 'Jawa Barat');
INSERT INTO `food` VALUES (442, 'Asinan Bogor', 'Jawa Barat');
INSERT INTO `food` VALUES (443, 'Bir Kocok (Jahe dikocok dengan es batu)', 'Jawa Barat');
INSERT INTO `food` VALUES (444, 'Laksa Bogor', 'Jawa Barat');
INSERT INTO `food` VALUES (445, 'Roti Unyil', 'Jawa Barat');
INSERT INTO `food` VALUES (446, 'Serabi Bogor', 'Jawa Barat');
INSERT INTO `food` VALUES (447, 'Soto Kuning', 'Jawa Barat');
INSERT INTO `food` VALUES (448, 'Soto Mi', 'Jawa Barat');
INSERT INTO `food` VALUES (449, 'Tauge Goreng', 'Jawa Barat');
INSERT INTO `food` VALUES (450, 'Toge Goreng Jasinga Bogor', 'Jawa Barat');
INSERT INTO `food` VALUES (451, 'Doclang', 'Jawa Barat');
INSERT INTO `food` VALUES (452, 'Ayam Goreng khas Sukabumi', 'Jawa Barat');
INSERT INTO `food` VALUES (453, 'Bubur ayam Bunut', 'Jawa Barat');
INSERT INTO `food` VALUES (454, 'Kue Jahe', 'Jawa Barat');
INSERT INTO `food` VALUES (455, 'Mochi', 'Jawa Barat');
INSERT INTO `food` VALUES (456, 'Sagon Bakar', 'Jawa Barat');
INSERT INTO `food` VALUES (457, 'Dodol Hideung Ketan', 'Jawa Barat');
INSERT INTO `food` VALUES (458, 'Gegeplak', 'Jawa Barat');
INSERT INTO `food` VALUES (459, 'Kue Ali (Kue Cincin)', 'Jawa Barat');
INSERT INTO `food` VALUES (460, 'Opak Ketan', 'Jawa Barat');
INSERT INTO `food` VALUES (461, 'Pepes', 'Jawa Barat');
INSERT INTO `food` VALUES (462, 'Rangginang Ketan', 'Jawa Barat');
INSERT INTO `food` VALUES (463, 'Semprong', 'Jawa Barat');
INSERT INTO `food` VALUES (464, 'Colenak', 'Jawa Barat');
INSERT INTO `food` VALUES (465, 'Gula Aren Cikeris', 'Jawa Barat');
INSERT INTO `food` VALUES (466, 'Manisan Pala', 'Jawa Barat');
INSERT INTO `food` VALUES (467, 'Nasi Timbel Ciganea', 'Jawa Barat');
INSERT INTO `food` VALUES (468, 'Opak', 'Jawa Barat');
INSERT INTO `food` VALUES (469, 'Peuyeum Bendul', 'Jawa Barat');
INSERT INTO `food` VALUES (470, 'Sate Maranggi', 'Jawa Barat');
INSERT INTO `food` VALUES (471, 'Simping', 'Jawa Barat');
INSERT INTO `food` VALUES (472, 'Soto Sadang', 'Jawa Barat');
INSERT INTO `food` VALUES (473, 'Teh Hijau', 'Jawa Barat');
INSERT INTO `food` VALUES (474, 'Bandeng presto', 'Jawa Tengah');
INSERT INTO `food` VALUES (475, 'Gudeg Koyor', 'Jawa Tengah');
INSERT INTO `food` VALUES (476, 'Lumpia Semarang', 'Jawa Tengah');
INSERT INTO `food` VALUES (477, 'Mie Tite', 'Jawa Tengah');
INSERT INTO `food` VALUES (478, 'Nasi Gandul', 'Jawa Tengah');
INSERT INTO `food` VALUES (479, 'Nasi Pindang', 'Jawa Tengah');
INSERT INTO `food` VALUES (480, 'Petis Kangkung', 'Jawa Tengah');
INSERT INTO `food` VALUES (481, 'Sate Sapi Ungaran', 'Jawa Tengah');
INSERT INTO `food` VALUES (482, 'Sego Ayam (Nasi Ayam)', 'Jawa Tengah');
INSERT INTO `food` VALUES (483, 'Sego Goreng Babat Semarang', 'Jawa Tengah');
INSERT INTO `food` VALUES (484, 'Soto Daging Sapi', 'Jawa Tengah');
INSERT INTO `food` VALUES (485, 'Soto Semarang', 'Jawa Tengah');
INSERT INTO `food` VALUES (486, 'Swiekee Kuah', 'Jawa Tengah');
INSERT INTO `food` VALUES (487, 'Tahu Gimbal', 'Jawa Tengah');
INSERT INTO `food` VALUES (488, 'Kupat tahu', 'Jawa Tengah');
INSERT INTO `food` VALUES (489, 'Tahu petis', 'Jawa Tengah');
INSERT INTO `food` VALUES (490, 'Tahu Pong', 'Jawa Tengah');
INSERT INTO `food` VALUES (491, 'Tahu Telur', 'Jawa Tengah');
INSERT INTO `food` VALUES (492, 'Lanting', 'Jawa Tengah');
INSERT INTO `food` VALUES (493, 'Soto Petanahan', 'Jawa Tengah');
INSERT INTO `food` VALUES (494, 'Soto Jogomertan', 'Jawa Tengah');
INSERT INTO `food` VALUES (495, 'Tongseng', 'Jawa Tengah');
INSERT INTO `food` VALUES (496, 'Sate Ambal', 'Jawa Tengah');
INSERT INTO `food` VALUES (497, 'Bebek Kremes', 'Jawa Tengah');
INSERT INTO `food` VALUES (498, 'Sate Sapi Plarangan', 'Jawa Tengah');
INSERT INTO `food` VALUES (499, 'Rica Rica', 'Jawa Tengah');
INSERT INTO `food` VALUES (500, 'Bunthil', 'Jawa Tengah');
INSERT INTO `food` VALUES (501, 'Ciwel', 'Jawa Tengah');
INSERT INTO `food` VALUES (502, 'Martabak Legi', 'Jawa Tengah');
INSERT INTO `food` VALUES (503, 'Lupis', 'Jawa Tengah');
INSERT INTO `food` VALUES (504, 'Cenil', 'Jawa Tengah');
INSERT INTO `food` VALUES (505, 'Jipang', 'Jawa Tengah');
INSERT INTO `food` VALUES (506, 'Es Kopyor', 'Jawa Tengah');
INSERT INTO `food` VALUES (507, 'Dawet Ireng', 'Jawa Tengah');
INSERT INTO `food` VALUES (508, 'Arem-arem', 'Jawa Tengah');
INSERT INTO `food` VALUES (509, 'Enting-enting', 'Jawa Tengah');
INSERT INTO `food` VALUES (510, 'Es Campur', 'Jawa Tengah');
INSERT INTO `food` VALUES (511, 'Kripik Laron', 'Jawa Tengah');
INSERT INTO `food` VALUES (512, 'Sate Suruh', 'Jawa Tengah');
INSERT INTO `food` VALUES (513, 'Es Cendol', 'Jawa Tengah');
INSERT INTO `food` VALUES (514, 'Nasi Godog', 'Jawa Tengah');
INSERT INTO `food` VALUES (515, 'Wedang Ronde', 'Jawa Tengah');
INSERT INTO `food` VALUES (516, 'Getuk', 'Jawa Tengah');
INSERT INTO `food` VALUES (517, 'Ndog Gludug', 'Jawa Tengah');
INSERT INTO `food` VALUES (518, 'Sumpil', 'Jawa Tengah');
INSERT INTO `food` VALUES (519, 'Riwit', 'Jawa Tengah');
INSERT INTO `food` VALUES (520, 'Cotot', 'Jawa Tengah');
INSERT INTO `food` VALUES (521, 'Tawonan', 'Jawa Tengah');
INSERT INTO `food` VALUES (522, 'Kupat Tahu', 'Jawa Tengah');
INSERT INTO `food` VALUES (523, 'Tape Ketan', 'Jawa Tengah');
INSERT INTO `food` VALUES (524, 'Wajik', 'Jawa Tengah');
INSERT INTO `food` VALUES (525, 'Nasi goreng Magelang', 'Jawa Tengah');
INSERT INTO `food` VALUES (526, 'Sego Godog', 'Jawa Tengah');
INSERT INTO `food` VALUES (527, 'Strewel', 'Jawa Tengah');
INSERT INTO `food` VALUES (528, 'Nagasari', 'Jawa Tengah');
INSERT INTO `food` VALUES (529, 'Nasi Jagung', 'Jawa Tengah');
INSERT INTO `food` VALUES (530, 'Slondok', 'Jawa Tengah');
INSERT INTO `food` VALUES (531, 'Mendoan', 'Jawa Tengah');
INSERT INTO `food` VALUES (532, 'Ingkung', 'Jawa Tengah');
INSERT INTO `food` VALUES (533, 'Sambel Tumpang', 'Jawa Tengah');
INSERT INTO `food` VALUES (534, 'Soto Daging Sapi', 'Jawa Tengah');
INSERT INTO `food` VALUES (535, 'Pecel Gendar', 'Jawa Tengah');
INSERT INTO `food` VALUES (536, 'Soto Ayam', 'Jawa Tengah');
INSERT INTO `food` VALUES (537, 'Tepo', 'Jawa Tengah');
INSERT INTO `food` VALUES (538, 'Antor Tegal', 'Jawa Tengah');
INSERT INTO `food` VALUES (539, 'Busro', 'Jawa Tengah');
INSERT INTO `food` VALUES (540, 'Dawet Beras & Aci', 'Jawa Tengah');
INSERT INTO `food` VALUES (541, 'Glotak', 'Jawa Tengah');
INSERT INTO `food` VALUES (542, 'Kacang Bogares', 'Jawa Tengah');
INSERT INTO `food` VALUES (543, 'Kacang Bogares', 'Jawa Tengah');
INSERT INTO `food` VALUES (544, 'Kerupuk Antor', 'Jawa Tengah');
INSERT INTO `food` VALUES (545, 'Kerupuk Mi', 'Jawa Tengah');
INSERT INTO `food` VALUES (546, 'Kupat Glabed', 'Jawa Tengah');
INSERT INTO `food` VALUES (547, 'Lengko', 'Jawa Tengah');
INSERT INTO `food` VALUES (548, 'Martabak Lebaksiu', 'Jawa Tengah');
INSERT INTO `food` VALUES (549, 'Olos', 'Jawa Tengah');
INSERT INTO `food` VALUES (550, 'Pilus', 'Jawa Tengah');
INSERT INTO `food` VALUES (551, 'Ponggol Setan', 'Jawa Tengah');
INSERT INTO `food` VALUES (552, 'Sate Itik Brebes', 'Jawa Tengah');
INSERT INTO `food` VALUES (553, 'Sate Kerang', 'Jawa Tengah');
INSERT INTO `food` VALUES (554, 'Sate Tegal', 'Jawa Tengah');
INSERT INTO `food` VALUES (555, 'Soto Tauco', 'Jawa Tengah');
INSERT INTO `food` VALUES (556, 'Soto Tegal', 'Jawa Tengah');
INSERT INTO `food` VALUES (557, 'Tahu Aci', 'Jawa Tengah');
INSERT INTO `food` VALUES (558, 'Tahu Pletok', 'Jawa Tengah');
INSERT INTO `food` VALUES (559, 'Teh Gopek', 'Jawa Tengah');
INSERT INTO `food` VALUES (560, 'Teh Poci', 'Jawa Tengah');
INSERT INTO `food` VALUES (561, 'Telur Asin Brebes', 'Jawa Tengah');
INSERT INTO `food` VALUES (562, 'Gethuk goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (563, 'Jenang Jaket', 'Jawa Tengah');
INSERT INTO `food` VALUES (564, 'Mino', 'Jawa Tengah');
INSERT INTO `food` VALUES (565, 'Nopya', 'Jawa Tengah');
INSERT INTO `food` VALUES (566, 'Sroto Sokaraja', 'Jawa Tengah');
INSERT INTO `food` VALUES (567, 'Tempe mendoan', 'Jawa Tengah');
INSERT INTO `food` VALUES (568, 'Bakmi Nyemek', 'Jawa Tengah');
INSERT INTO `food` VALUES (569, 'Cimplung', 'Jawa Tengah');
INSERT INTO `food` VALUES (570, 'Getuk', 'Jawa Tengah');
INSERT INTO `food` VALUES (571, 'Kraca Cenil', 'Jawa Tengah');
INSERT INTO `food` VALUES (572, 'Petis Enthog', 'Jawa Tengah');
INSERT INTO `food` VALUES (573, 'Sate Bebek', 'Jawa Tengah');
INSERT INTO `food` VALUES (574, 'Sate Sapi', 'Jawa Tengah');
INSERT INTO `food` VALUES (575, 'Tegean', 'Jawa Tengah');
INSERT INTO `food` VALUES (576, 'Tuak Badeg', 'Jawa Tengah');
INSERT INTO `food` VALUES (577, 'Lontong sayur', 'Jawa Tengah');
INSERT INTO `food` VALUES (578, 'Nasi Megono', 'Jawa Tengah');
INSERT INTO `food` VALUES (579, 'Soto Pekalongan', 'Jawa Tengah');
INSERT INTO `food` VALUES (580, 'Pindang Tetel', 'Jawa Tengah');
INSERT INTO `food` VALUES (581, 'Adon-Adon Coro', 'Jawa Tengah');
INSERT INTO `food` VALUES (582, 'Carang Madu', 'Jawa Tengah');
INSERT INTO `food` VALUES (583, 'Rujak Degan', 'Jawa Tengah');
INSERT INTO `food` VALUES (584, 'Es Dawet', 'Jawa Tengah');
INSERT INTO `food` VALUES (585, 'Es Gempol', 'Jawa Tengah');
INSERT INTO `food` VALUES (586, 'Horok-Horok', 'Jawa Tengah');
INSERT INTO `food` VALUES (587, 'Kacang Jepara', 'Jawa Tengah');
INSERT INTO `food` VALUES (588, 'Kacang Oven', 'Jawa Tengah');
INSERT INTO `food` VALUES (589, 'Keciput', 'Jawa Tengah');
INSERT INTO `food` VALUES (590, 'Kerupuk Kerapu', 'Jawa Tengah');
INSERT INTO `food` VALUES (591, 'Kue Bangket', 'Jawa Tengah');
INSERT INTO `food` VALUES (592, 'Lontong Campur', 'Jawa Tengah');
INSERT INTO `food` VALUES (593, 'Nasi Tempong', 'Jawa Tengah');
INSERT INTO `food` VALUES (594, 'Pecel Ikan Laut Panggang', 'Jawa Tengah');
INSERT INTO `food` VALUES (595, 'Pindang Serani', 'Jawa Tengah');
INSERT INTO `food` VALUES (596, 'Sate Kikil', 'Jawa Tengah');
INSERT INTO `food` VALUES (597, 'Sop Udang', 'Jawa Tengah');
INSERT INTO `food` VALUES (598, 'Soto Jepara', 'Jawa Tengah');
INSERT INTO `food` VALUES (599, 'cecek', 'Jawa Tengah');
INSERT INTO `food` VALUES (600, 'cetot', 'Jawa Tengah');
INSERT INTO `food` VALUES (601, 'Bandeng presto', 'Jawa Tengah');
INSERT INTO `food` VALUES (602, 'Nasi gandul', 'Jawa Tengah');
INSERT INTO `food` VALUES (603, 'Soto kemiri', 'Jawa Tengah');
INSERT INTO `food` VALUES (604, 'Petis Tangkar', 'Jawa Tengah');
INSERT INTO `food` VALUES (605, 'Gethuk Runting', 'Jawa Tengah');
INSERT INTO `food` VALUES (606, 'Lopis', 'Jawa Tengah');
INSERT INTO `food` VALUES (607, 'Garang Asem', 'Jawa Tengah');
INSERT INTO `food` VALUES (608, 'jenang kudus', 'Jawa Tengah');
INSERT INTO `food` VALUES (609, 'Lentog', 'Jawa Tengah');
INSERT INTO `food` VALUES (610, 'Nasi Grombyang', 'Jawa Tengah');
INSERT INTO `food` VALUES (611, 'Nasi megono', 'Jawa Tengah');
INSERT INTO `food` VALUES (612, 'Nasi pindang', 'Jawa Tengah');
INSERT INTO `food` VALUES (613, 'Soto Kudus', 'Jawa Tengah');
INSERT INTO `food` VALUES (614, 'Taoto', 'Jawa Tengah');
INSERT INTO `food` VALUES (615, 'Pecel Pakis', 'Jawa Tengah');
INSERT INTO `food` VALUES (616, 'Dumbeg', 'Jawa Tengah');
INSERT INTO `food` VALUES (617, 'Gula Semut', 'Jawa Tengah');
INSERT INTO `food` VALUES (618, 'Jadah', 'Jawa Tengah');
INSERT INTO `food` VALUES (619, 'Jenang Waluh', 'Jawa Tengah');
INSERT INTO `food` VALUES (620, 'Kacang Atom', 'Jawa Tengah');
INSERT INTO `food` VALUES (621, 'Kacang Pres', 'Jawa Tengah');
INSERT INTO `food` VALUES (622, 'Kaoya Dudul', 'Jawa Tengah');
INSERT INTO `food` VALUES (623, 'Kerupuk Bakar', 'Jawa Tengah');
INSERT INTO `food` VALUES (624, 'Lontong Tuyuhan', 'Jawa Tengah');
INSERT INTO `food` VALUES (625, 'Mangut', 'Jawa Tengah');
INSERT INTO `food` VALUES (626, 'Petis Bumbon', 'Jawa Tengah');
INSERT INTO `food` VALUES (627, 'Pindang Tempe', 'Jawa Tengah');
INSERT INTO `food` VALUES (628, 'Sate Sarepeh', 'Jawa Tengah');
INSERT INTO `food` VALUES (629, 'Sayur Merica', 'Jawa Tengah');
INSERT INTO `food` VALUES (630, 'Terasi Petis Bonang', 'Jawa Tengah');
INSERT INTO `food` VALUES (631, 'Rawon', 'Jawa Tengah');
INSERT INTO `food` VALUES (632, 'Sate Ayam Blora', 'Jawa Tengah');
INSERT INTO `food` VALUES (633, 'Tahu Lontong', 'Jawa Tengah');
INSERT INTO `food` VALUES (634, 'Botok Telur Asin', 'Jawa Tengah');
INSERT INTO `food` VALUES (635, 'Nasi Ndoreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (636, 'Wedang Pekak', 'Jawa Tengah');
INSERT INTO `food` VALUES (637, 'Abon Varia', 'Jawa Tengah');
INSERT INTO `food` VALUES (638, 'Ampyang Kacang', 'Jawa Tengah');
INSERT INTO `food` VALUES (639, 'Ampyang', 'Jawa Tengah');
INSERT INTO `food` VALUES (640, 'Ayam Areh', 'Jawa Tengah');
INSERT INTO `food` VALUES (641, 'Bakmi Ketoprak', 'Jawa Tengah');
INSERT INTO `food` VALUES (642, 'Bebek Balap', 'Jawa Tengah');
INSERT INTO `food` VALUES (643, 'Beras Kencur', 'Jawa Tengah');
INSERT INTO `food` VALUES (644, 'Bubur Kacang Ijo', 'Jawa Tengah');
INSERT INTO `food` VALUES (645, 'Cabuk Rambak', 'Jawa Tengah');
INSERT INTO `food` VALUES (646, 'Carang Gesing', 'Jawa Tengah');
INSERT INTO `food` VALUES (647, 'Dawet Ayu', 'Jawa Tengah');
INSERT INTO `food` VALUES (648, 'Dawet', 'Jawa Tengah');
INSERT INTO `food` VALUES (649, 'Es Puter', 'Jawa Tengah');
INSERT INTO `food` VALUES (650, 'Garang Asem', 'Jawa Tengah');
INSERT INTO `food` VALUES (651, 'Gempol Plered', 'Jawa Tengah');
INSERT INTO `food` VALUES (652, 'Gudeg', 'Jawa Tengah');
INSERT INTO `food` VALUES (653, 'Gule Goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (654, 'Intip Goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (655, 'Jadah Blondo', 'Jawa Tengah');
INSERT INTO `food` VALUES (656, 'Karak', 'Jawa Tengah');
INSERT INTO `food` VALUES (657, 'Kawis Cao', 'Jawa Tengah');
INSERT INTO `food` VALUES (658, 'Kulit Ayam Goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (659, 'Mi Toprak', 'Jawa Tengah');
INSERT INTO `food` VALUES (660, 'Nasi Langgi', 'Jawa Tengah');
INSERT INTO `food` VALUES (661, 'Nasi Liwet', 'Jawa Tengah');
INSERT INTO `food` VALUES (662, 'Nasi Tumpang', 'Jawa Tengah');
INSERT INTO `food` VALUES (663, 'Roti Kecik', 'Jawa Tengah');
INSERT INTO `food` VALUES (664, 'Roti Mandarin', 'Jawa Tengah');
INSERT INTO `food` VALUES (665, 'Roti Semir', 'Jawa Tengah');
INSERT INTO `food` VALUES (666, 'Sambel Tumpang', 'Jawa Tengah');
INSERT INTO `food` VALUES (667, 'Sate Buntel', 'Jawa Tengah');
INSERT INTO `food` VALUES (668, 'Sayur Labu Siam', 'Jawa Tengah');
INSERT INTO `food` VALUES (669, 'Selat Solo', 'Jawa Tengah');
INSERT INTO `food` VALUES (670, 'Semar Mendem', 'Jawa Tengah');
INSERT INTO `food` VALUES (671, 'Serabi Notosuman', 'Jawa Tengah');
INSERT INTO `food` VALUES (672, 'Serbat', 'Jawa Tengah');
INSERT INTO `food` VALUES (673, 'Sosis Solo', 'Jawa Tengah');
INSERT INTO `food` VALUES (674, 'Soto Gading', 'Jawa Tengah');
INSERT INTO `food` VALUES (675, 'Srabi Solo', 'Jawa Tengah');
INSERT INTO `food` VALUES (676, 'Tahu Acar', 'Jawa Tengah');
INSERT INTO `food` VALUES (677, 'Tahu Kupat', 'Jawa Tengah');
INSERT INTO `food` VALUES (678, 'Tempe Tahu Bacem', 'Jawa Tengah');
INSERT INTO `food` VALUES (679, 'Tengkleng', 'Jawa Tengah');
INSERT INTO `food` VALUES (680, 'Timlo', 'Jawa Tengah');
INSERT INTO `food` VALUES (681, 'Tongseng', 'Jawa Tengah');
INSERT INTO `food` VALUES (682, 'Usus Goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (683, 'Wedang Dongo', 'Jawa Tengah');
INSERT INTO `food` VALUES (684, 'Wedang Jahe', 'Jawa Tengah');
INSERT INTO `food` VALUES (685, 'Abangan', 'Jawa Tengah');
INSERT INTO `food` VALUES (686, 'Alen alen', 'Jawa Tengah');
INSERT INTO `food` VALUES (687, 'Ampyang', 'Jawa Tengah');
INSERT INTO `food` VALUES (688, 'Ayam Bacem', 'Jawa Tengah');
INSERT INTO `food` VALUES (689, 'Ayam Kalasan', 'Jawa Tengah');
INSERT INTO `food` VALUES (690, 'Bakmi Godog', 'Jawa Tengah');
INSERT INTO `food` VALUES (691, 'Bakmi Jawa', 'Jawa Tengah');
INSERT INTO `food` VALUES (692, 'Bakmoy', 'Jawa Tengah');
INSERT INTO `food` VALUES (693, 'Bakpia', 'Jawa Tengah');
INSERT INTO `food` VALUES (694, 'Bebek Suwar-Suwir', 'Jawa Tengah');
INSERT INTO `food` VALUES (695, 'Beer Djawa', 'Jawa Tengah');
INSERT INTO `food` VALUES (696, 'Bunthil', 'Jawa Tengah');
INSERT INTO `food` VALUES (697, 'Cabuk Rambak', 'Jawa Tengah');
INSERT INTO `food` VALUES (698, 'Carang Gesing', 'Jawa Tengah');
INSERT INTO `food` VALUES (699, 'Cemplon', 'Jawa Tengah');
INSERT INTO `food` VALUES (700, 'Cenil', 'Jawa Tengah');
INSERT INTO `food` VALUES (701, 'Dendeng Age', 'Jawa Tengah');
INSERT INTO `food` VALUES (702, 'Enting-enting', 'Jawa Tengah');
INSERT INTO `food` VALUES (703, 'Gado-Gado', 'Jawa Tengah');
INSERT INTO `food` VALUES (704, 'Gaplek', 'Jawa Tengah');
INSERT INTO `food` VALUES (705, 'Gathot', 'Jawa Tengah');
INSERT INTO `food` VALUES (706, 'Geplak', 'Jawa Tengah');
INSERT INTO `food` VALUES (707, 'Getuk', 'Jawa Tengah');
INSERT INTO `food` VALUES (708, 'Growol', 'Jawa Tengah');
INSERT INTO `food` VALUES (709, 'Gudangan', 'Jawa Tengah');
INSERT INTO `food` VALUES (710, 'Gudeg Nangka', 'Jawa Tengah');
INSERT INTO `food` VALUES (711, 'Gudeg Manggar', 'Jawa Tengah');
INSERT INTO `food` VALUES (712, 'Jadah Bacem', 'Jawa Tengah');
INSERT INTO `food` VALUES (713, 'Jadah Manten', 'Jawa Tengah');
INSERT INTO `food` VALUES (714, 'Jamu Beras Kencur', 'Jawa Tengah');
INSERT INTO `food` VALUES (715, 'Jamu Kunir Asem', 'Jawa Tengah');
INSERT INTO `food` VALUES (716, 'Jenang Gronthol', 'Jawa Tengah');
INSERT INTO `food` VALUES (717, 'Jenang Rumput laut', 'Jawa Tengah');
INSERT INTO `food` VALUES (718, 'Jenang Sungsum', 'Jawa Tengah');
INSERT INTO `food` VALUES (719, 'Juwawut', 'Jawa Tengah');
INSERT INTO `food` VALUES (720, 'Kipo', 'Jawa Tengah');
INSERT INTO `food` VALUES (721, 'Klepon', 'Jawa Tengah');
INSERT INTO `food` VALUES (722, 'kopi Jos arang', 'Jawa Tengah');
INSERT INTO `food` VALUES (723, 'Legomoro', 'Jawa Tengah');
INSERT INTO `food` VALUES (724, 'Lempeng Legendar', 'Jawa Tengah');
INSERT INTO `food` VALUES (725, 'Lempeng Telo', 'Jawa Tengah');
INSERT INTO `food` VALUES (726, 'Lontong Kikil', 'Jawa Tengah');
INSERT INTO `food` VALUES (727, 'Lumpia Trubus', 'Jawa Tengah');
INSERT INTO `food` VALUES (728, 'Mangut Lele', 'Jawa Tengah');
INSERT INTO `food` VALUES (729, 'Mata Kebo', 'Jawa Tengah');
INSERT INTO `food` VALUES (730, 'Mega Mendung', 'Jawa Tengah');
INSERT INTO `food` VALUES (731, 'Mendut', 'Jawa Tengah');
INSERT INTO `food` VALUES (732, 'Mi Tektek', 'Jawa Tengah');
INSERT INTO `food` VALUES (733, 'Nasi Goreng Magelang', 'Jawa Tengah');
INSERT INTO `food` VALUES (734, 'Nasi Kucing', 'Jawa Tengah');
INSERT INTO `food` VALUES (735, 'Nasi Pecel', 'Jawa Tengah');
INSERT INTO `food` VALUES (736, 'Nasi Wiwit', 'Jawa Tengah');
INSERT INTO `food` VALUES (737, 'Ndog Gludug', 'Jawa Tengah');
INSERT INTO `food` VALUES (738, 'Onde-onde', 'Jawa Tengah');
INSERT INTO `food` VALUES (739, 'Ongol-ongol', 'Jawa Tengah');
INSERT INTO `food` VALUES (740, 'Opor Ayam', 'Jawa Tengah');
INSERT INTO `food` VALUES (741, 'Opor Telur', 'Jawa Tengah');
INSERT INTO `food` VALUES (742, 'Pecel', 'Jawa Tengah');
INSERT INTO `food` VALUES (743, 'Peyek Bayem', 'Jawa Tengah');
INSERT INTO `food` VALUES (744, 'Peyek Dele', 'Jawa Tengah');
INSERT INTO `food` VALUES (745, 'Peyek Jingking', 'Jawa Tengah');
INSERT INTO `food` VALUES (746, 'Peyek Kacang', 'Jawa Tengah');
INSERT INTO `food` VALUES (747, 'Rengginang', 'Jawa Tengah');
INSERT INTO `food` VALUES (748, 'Roti Jok', 'Jawa Tengah');
INSERT INTO `food` VALUES (749, 'Rujak Degan', 'Jawa Tengah');
INSERT INTO `food` VALUES (750, 'Sagon Kota Gede', 'Jawa Tengah');
INSERT INTO `food` VALUES (751, 'Sambal Goreng Krecek Kacang Tolo', 'Jawa Tengah');
INSERT INTO `food` VALUES (752, 'Sambel Goreng Krecek', 'Jawa Tengah');
INSERT INTO `food` VALUES (753, 'Sate Klathak', 'Jawa Tengah');
INSERT INTO `food` VALUES (754, 'Sate Kocor', 'Jawa Tengah');
INSERT INTO `food` VALUES (755, 'Sate Manis', 'Jawa Tengah');
INSERT INTO `food` VALUES (756, 'Sate Winong', 'Jawa Tengah');
INSERT INTO `food` VALUES (757, 'Sego Abang', 'Jawa Tengah');
INSERT INTO `food` VALUES (758, 'Selat', 'Jawa Tengah');
INSERT INTO `food` VALUES (759, 'Semar Mesem', 'Jawa Tengah');
INSERT INTO `food` VALUES (760, 'Srabi Kocor', 'Jawa Tengah');
INSERT INTO `food` VALUES (761, 'Tempe Benguk', 'Jawa Tengah');
INSERT INTO `food` VALUES (762, 'Tempe Gembus', 'Jawa Tengah');
INSERT INTO `food` VALUES (763, 'Tempe Koro', 'Jawa Tengah');
INSERT INTO `food` VALUES (764, 'Timus', 'Jawa Tengah');
INSERT INTO `food` VALUES (765, 'Thiwul', 'Jawa Tengah');
INSERT INTO `food` VALUES (766, 'Tongseng', 'Jawa Tengah');
INSERT INTO `food` VALUES (767, 'Trancam', 'Jawa Tengah');
INSERT INTO `food` VALUES (768, 'Trasikan', 'Jawa Tengah');
INSERT INTO `food` VALUES (769, 'Tumpeng', 'Jawa Tengah');
INSERT INTO `food` VALUES (770, 'Urap', 'Jawa Tengah');
INSERT INTO `food` VALUES (771, 'Ungrung', 'Jawa Tengah');
INSERT INTO `food` VALUES (772, 'Wajik', 'Jawa Tengah');
INSERT INTO `food` VALUES (773, 'Walang Goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (774, 'Wedang Ronde', 'Jawa Tengah');
INSERT INTO `food` VALUES (775, 'Wedang Secang', 'Jawa Tengah');
INSERT INTO `food` VALUES (776, 'Wedang Uwuh', 'Jawa Tengah');
INSERT INTO `food` VALUES (777, 'Yangko', 'Jawa Tengah');
INSERT INTO `food` VALUES (778, 'Geplak', 'Jawa Tengah');
INSERT INTO `food` VALUES (779, 'Gudeg Manggar', 'Jawa Tengah');
INSERT INTO `food` VALUES (780, 'Bakmi Pentil', 'Jawa Tengah');
INSERT INTO `food` VALUES (781, 'Bakmi Letheg', 'Jawa Tengah');
INSERT INTO `food` VALUES (782, 'Miedes (Bakmi Pedes', 'Jawa Tengah');
INSERT INTO `food` VALUES (783, 'Tolpit', 'Jawa Tengah');
INSERT INTO `food` VALUES (784, 'Sate Klathak', 'Jawa Tengah');
INSERT INTO `food` VALUES (785, 'Peyek Undur-undur', 'Jawa Tengah');
INSERT INTO `food` VALUES (786, 'Peyek Tumpuk', 'Jawa Tengah');
INSERT INTO `food` VALUES (787, 'Karangan', 'Jawa Tengah');
INSERT INTO `food` VALUES (788, 'Wedang Uwuh', 'Jawa Tengah');
INSERT INTO `food` VALUES (789, 'Jadah Tempe', 'Jawa Tengah');
INSERT INTO `food` VALUES (790, 'Thiwul', 'Jawa Tengah');
INSERT INTO `food` VALUES (791, 'Gathot', 'Jawa Tengah');
INSERT INTO `food` VALUES (792, 'Gaplek', 'Jawa Tengah');
INSERT INTO `food` VALUES (793, 'Ungrung', 'Jawa Tengah');
INSERT INTO `food` VALUES (794, 'Walang Goreng', 'Jawa Tengah');
INSERT INTO `food` VALUES (795, 'Growol', 'Jawa Tengah');
INSERT INTO `food` VALUES (796, 'Geblek', 'Jawa Tengah');
INSERT INTO `food` VALUES (797, 'Gudeg', 'Jawa Tengah');
INSERT INTO `food` VALUES (798, 'Brongkos', 'Jawa Tengah');
INSERT INTO `food` VALUES (799, 'Rawon', 'Jawa Timur');
INSERT INTO `food` VALUES (800, 'Lontong Balap', 'Jawa Timur');
INSERT INTO `food` VALUES (801, 'Bebek Goreng', 'Jawa Timur');
INSERT INTO `food` VALUES (802, 'Pecel Surabaya', 'Jawa Timur');
INSERT INTO `food` VALUES (803, 'Rujak Cingur', 'Jawa Timur');
INSERT INTO `food` VALUES (804, 'Rujak Uleg', 'Jawa Timur');
INSERT INTO `food` VALUES (805, 'Rujak Legi (Rujak Manis)', 'Jawa Timur');
INSERT INTO `food` VALUES (806, 'Semanggi', 'Jawa Timur');
INSERT INTO `food` VALUES (807, 'Tahu Lontong', 'Jawa Timur');
INSERT INTO `food` VALUES (808, 'Tahu Tek', 'Jawa Timur');
INSERT INTO `food` VALUES (809, 'Teh Kocok', 'Jawa Timur');
INSERT INTO `food` VALUES (810, 'Kue cucur', 'Jawa Timur');
INSERT INTO `food` VALUES (811, 'Spikoe', 'Jawa Timur');
INSERT INTO `food` VALUES (812, 'Lapis Kukus', 'Jawa Timur');
INSERT INTO `food` VALUES (813, 'Lontong Kupang', 'Jawa Timur');
INSERT INTO `food` VALUES (814, 'Lontong Cecek', 'Jawa Timur');
INSERT INTO `food` VALUES (815, 'Sate kerang', 'Jawa Timur');
INSERT INTO `food` VALUES (816, 'Otak otak bandeng', 'Jawa Timur');
INSERT INTO `food` VALUES (817, 'Kerupuk udang', 'Jawa Timur');
INSERT INTO `food` VALUES (818, 'Bandeng asap', 'Jawa Timur');
INSERT INTO `food` VALUES (819, 'Bandeng presto', 'Jawa Timur');
INSERT INTO `food` VALUES (820, 'Petis', 'Jawa Timur');
INSERT INTO `food` VALUES (821, 'Lontong balap', 'Jawa Timur');
INSERT INTO `food` VALUES (822, 'Kupang Lontong', 'Jawa Timur');
INSERT INTO `food` VALUES (823, 'Weci', 'Jawa Timur');
INSERT INTO `food` VALUES (824, 'Menjes', 'Jawa Timur');
INSERT INTO `food` VALUES (825, 'Oseng-oseng', 'Jawa Timur');
INSERT INTO `food` VALUES (826, 'Sayur Kelor', 'Jawa Timur');
INSERT INTO `food` VALUES (827, 'Onde-onde', 'Jawa Timur');
INSERT INTO `food` VALUES (828, 'Kerupuk Rambak', 'Jawa Timur');
INSERT INTO `food` VALUES (829, 'Sate Ayam Ponorogo', 'Jawa Timur');
INSERT INTO `food` VALUES (830, 'Nasi Pecel', 'Jawa Timur');
INSERT INTO `food` VALUES (831, 'Soto Lamongan', 'Jawa Timur');
INSERT INTO `food` VALUES (832, 'Nasi Boran', 'Jawa Timur');
INSERT INTO `food` VALUES (833, 'Tahu campur', 'Jawa Timur');
INSERT INTO `food` VALUES (834, 'Tahu Tek', 'Jawa Timur');
INSERT INTO `food` VALUES (835, 'Lodeh kikil', 'Jawa Timur');
INSERT INTO `food` VALUES (836, 'iwak peyek', 'Jawa Timur');
INSERT INTO `food` VALUES (837, 'tiwul', 'Jawa Timur');
INSERT INTO `food` VALUES (838, 'sate semen', 'Jawa Timur');
INSERT INTO `food` VALUES (839, 'Jenang Jombang', 'Jawa Timur');
INSERT INTO `food` VALUES (840, 'Soto Kediri', 'Jawa Timur');
INSERT INTO `food` VALUES (841, 'Sambel Tumpang', 'Jawa Timur');
INSERT INTO `food` VALUES (842, 'Tahu Kuning', 'Jawa Timur');
INSERT INTO `food` VALUES (843, 'Stick Tahu', 'Jawa Timur');
INSERT INTO `food` VALUES (844, 'Gethuk Pisang', 'Jawa Timur');
INSERT INTO `food` VALUES (845, 'Sate, Keripik Bekicot', 'Jawa Timur');
INSERT INTO `food` VALUES (846, 'Kerupuk Puli', 'Jawa Timur');
INSERT INTO `food` VALUES (847, 'Rujak Soto', 'Jawa Timur');
INSERT INTO `food` VALUES (848, 'Nasi Tempong', 'Jawa Timur');
INSERT INTO `food` VALUES (849, 'Kue Bakiak', 'Jawa Timur');
INSERT INTO `food` VALUES (850, 'Pecel Phitik', 'Jawa Timur');
INSERT INTO `food` VALUES (851, 'Sayur Kesrut', 'Jawa Timur');
INSERT INTO `food` VALUES (852, 'Sego Kuning', 'Jawa Timur');
INSERT INTO `food` VALUES (853, 'Sego Kucing', 'Jawa Timur');
INSERT INTO `food` VALUES (854, 'Jangan Pakis', 'Jawa Timur');
INSERT INTO `food` VALUES (855, 'Koyong Lemuru', 'Jawa Timur');
INSERT INTO `food` VALUES (856, 'Pelasan', 'Jawa Timur');
INSERT INTO `food` VALUES (857, 'Pindang Koyong', 'Jawa Timur');
INSERT INTO `food` VALUES (858, 'Urap - Urap', 'Jawa Timur');
INSERT INTO `food` VALUES (859, 'Uceng uceng', 'Jawa Timur');
INSERT INTO `food` VALUES (860, 'Awok', 'Jawa Timur');
INSERT INTO `food` VALUES (861, 'Bothok', 'Jawa Timur');
INSERT INTO `food` VALUES (862, 'Orok - orok', 'Jawa Timur');
INSERT INTO `food` VALUES (863, 'Kucur', 'Jawa Timur');
INSERT INTO `food` VALUES (864, 'Jongkong Ijo', 'Jawa Timur');
INSERT INTO `food` VALUES (865, 'Nogo Sari', 'Jawa Timur');
INSERT INTO `food` VALUES (866, 'Bikang', 'Jawa Timur');
INSERT INTO `food` VALUES (867, 'Lempog', 'Jawa Timur');
INSERT INTO `food` VALUES (868, 'Lemper', 'Jawa Timur');
INSERT INTO `food` VALUES (869, 'Bungkuk', 'Jawa Timur');
INSERT INTO `food` VALUES (870, 'Lemet', 'Jawa Timur');
INSERT INTO `food` VALUES (871, 'Lanun', 'Jawa Timur');
INSERT INTO `food` VALUES (872, 'Lupis', 'Jawa Timur');
INSERT INTO `food` VALUES (873, 'Blendung', 'Jawa Timur');
INSERT INTO `food` VALUES (874, 'Jemblem', 'Jawa Timur');
INSERT INTO `food` VALUES (875, 'Sawot', 'Jawa Timur');
INSERT INTO `food` VALUES (876, 'Pukis', 'Jawa Timur');
INSERT INTO `food` VALUES (877, 'Rujak Cemplong', 'Jawa Timur');
INSERT INTO `food` VALUES (878, 'Rujak Kecut', 'Jawa Timur');
INSERT INTO `food` VALUES (879, 'Rujak Lontong', 'Jawa Timur');
INSERT INTO `food` VALUES (880, 'Rujak Sayur', 'Jawa Timur');
INSERT INTO `food` VALUES (881, 'Rujak Uni', 'Jawa Timur');
INSERT INTO `food` VALUES (882, 'Rujak Petis', 'Jawa Timur');
INSERT INTO `food` VALUES (883, 'Rujak Manis', 'Jawa Timur');
INSERT INTO `food` VALUES (884, 'Rujak Lethok', 'Jawa Timur');
INSERT INTO `food` VALUES (885, 'Rujak Gobet', 'Jawa Timur');
INSERT INTO `food` VALUES (886, 'Ragi Pelasan', 'Jawa Timur');
INSERT INTO `food` VALUES (887, 'Pare', 'Jawa Timur');
INSERT INTO `food` VALUES (888, 'Tempe Goreng', 'Jawa Timur');
INSERT INTO `food` VALUES (889, 'Gerang Tempe', 'Jawa Timur');
INSERT INTO `food` VALUES (890, 'Tempe Gembos', 'Jawa Timur');
INSERT INTO `food` VALUES (891, 'Pelasan Nus', 'Jawa Timur');
INSERT INTO `food` VALUES (892, 'Jangan Kelor', 'Jawa Timur');
INSERT INTO `food` VALUES (893, 'Sambel Ijo', 'Jawa Timur');
INSERT INTO `food` VALUES (894, 'Pecel Madiun', 'Jawa Timur');
INSERT INTO `food` VALUES (895, 'Brem', 'Jawa Timur');
INSERT INTO `food` VALUES (896, 'Sate Kelinci', 'Jawa Timur');
INSERT INTO `food` VALUES (897, 'Jerangking', 'Jawa Timur');
INSERT INTO `food` VALUES (898, 'Bolu Rahayu', 'Jawa Timur');
INSERT INTO `food` VALUES (899, 'Lempeng', 'Jawa Timur');
INSERT INTO `food` VALUES (900, 'Jenang Apel', 'Jawa Timur');
INSERT INTO `food` VALUES (901, 'Gado Gado', 'Jawa Timur');
INSERT INTO `food` VALUES (902, 'Sego Gobyos', 'Jawa Timur');
INSERT INTO `food` VALUES (903, 'Bata Anget', 'Jawa Timur');
INSERT INTO `food` VALUES (904, 'Pottre Nyellem', 'Jawa Timur');
INSERT INTO `food` VALUES (905, 'Nom Aeng', 'Jawa Timur');
INSERT INTO `food` VALUES (906, 'Pokak Syarifah', 'Jawa Timur');
INSERT INTO `food` VALUES (907, 'Wedang Sekojo', 'Jawa Timur');
INSERT INTO `food` VALUES (908, 'Lepet Jagung', 'Jawa Timur');
INSERT INTO `food` VALUES (909, 'Bakso Malang', 'Jawa Timur');
INSERT INTO `food` VALUES (910, 'Keripik Kentang', 'Jawa Timur');
INSERT INTO `food` VALUES (911, 'Keripik Singkong', 'Jawa Timur');
INSERT INTO `food` VALUES (912, 'Keripik Tempe', 'Jawa Timur');
INSERT INTO `food` VALUES (913, 'Angsle', 'Jawa Timur');
INSERT INTO `food` VALUES (914, 'Bakwan Malang', 'Jawa Timur');
INSERT INTO `food` VALUES (915, 'Puthu Lanang', 'Jawa Timur');
INSERT INTO `food` VALUES (916, 'Rujak Cingur', 'Jawa Timur');
INSERT INTO `food` VALUES (917, 'Tahu Tek', 'Jawa Timur');
INSERT INTO `food` VALUES (918, 'Nasi Mawut', 'Jawa Timur');
INSERT INTO `food` VALUES (919, 'Cwie Mie Malang', 'Jawa Timur');
INSERT INTO `food` VALUES (920, 'STMJ', 'Jawa Timur');
INSERT INTO `food` VALUES (921, 'Ronde', 'Jawa Timur');
INSERT INTO `food` VALUES (922, 'Es Mocca', 'Jawa Timur');
INSERT INTO `food` VALUES (923, 'Es Duren', 'Jawa Timur');
INSERT INTO `food` VALUES (924, 'Orem Orem', 'Jawa Timur');
INSERT INTO `food` VALUES (925, 'Mendol', 'Jawa Timur');
INSERT INTO `food` VALUES (926, 'Nasi Krawu', 'Jawa Timur');
INSERT INTO `food` VALUES (927, 'Nasi Blawu', 'Jawa Timur');
INSERT INTO `food` VALUES (928, 'Rempih Danggur', 'Jawa Timur');
INSERT INTO `food` VALUES (929, 'Tahu Wa', 'Jawa Timur');
INSERT INTO `food` VALUES (930, 'Teh Jahe Keningar', 'Jawa Timur');
INSERT INTO `food` VALUES (931, 'Tempe Penyet', 'Jawa Timur');
INSERT INTO `food` VALUES (932, 'Sego Tempong', 'Jawa Timur');
INSERT INTO `food` VALUES (933, 'Es Karet', 'Jawa Timur');
INSERT INTO `food` VALUES (934, 'Nasi Boranan', 'Jawa Timur');
INSERT INTO `food` VALUES (935, 'Nasi Becek', 'Jawa Timur');
INSERT INTO `food` VALUES (936, 'Keripik Tempe', 'Jawa Timur');
INSERT INTO `food` VALUES (937, 'Tape (Tapai)', 'Jawa Timur');
INSERT INTO `food` VALUES (938, 'Suwar-suwir', 'Jawa Timur');
INSERT INTO `food` VALUES (939, 'Ledre (kue/keripik pisang raja)', 'Jawa Timur');
INSERT INTO `food` VALUES (940, 'Gulai', 'Jawa Timur');
INSERT INTO `food` VALUES (941, 'Ja\'pe Ayam', 'Jawa Timur');
INSERT INTO `food` VALUES (942, 'Massa\'pote', 'Jawa Timur');
INSERT INTO `food` VALUES (943, 'Pedda', 'Jawa Timur');
INSERT INTO `food` VALUES (944, 'Gangsa', 'Jawa Timur');
INSERT INTO `food` VALUES (945, 'Maghadip', 'Jawa Timur');
INSERT INTO `food` VALUES (946, 'Putre Nyelem', 'Jawa Timur');
INSERT INTO `food` VALUES (947, 'Nomoeng', 'Jawa Timur');
INSERT INTO `food` VALUES (948, 'Klepon', 'Jawa Timur');
INSERT INTO `food` VALUES (949, 'Podak', 'Jawa Timur');
INSERT INTO `food` VALUES (950, 'Sate', 'Jawa Timur');
INSERT INTO `food` VALUES (951, 'Sate lalat', 'Jawa Timur');
INSERT INTO `food` VALUES (952, 'Bongko', 'Jawa Timur');
INSERT INTO `food` VALUES (953, 'Nase\' Serpang', 'Jawa Timur');
INSERT INTO `food` VALUES (954, 'Tajin Shobih', 'Jawa Timur');
INSERT INTO `food` VALUES (955, 'Karak', 'Jawa Timur');
INSERT INTO `food` VALUES (956, 'Lepet', 'Jawa Timur');
INSERT INTO `food` VALUES (957, 'Dudul', 'Jawa Timur');
INSERT INTO `food` VALUES (958, 'Soto Madura', 'Jawa Timur');
INSERT INTO `food` VALUES (959, 'Bubur Madura', 'Jawa Timur');
INSERT INTO `food` VALUES (960, 'Belut Pedas', 'Jawa Timur');
INSERT INTO `food` VALUES (961, 'Kare Rajungan', 'Jawa Timur');
INSERT INTO `food` VALUES (962, 'Becek Menthok', 'Jawa Timur');
INSERT INTO `food` VALUES (963, 'Asem-asem Ndas Manyung', 'Jawa Timur');
INSERT INTO `food` VALUES (964, 'Mangut Pee', 'Jawa Timur');
INSERT INTO `food` VALUES (965, 'Jangan Kelor', 'Jawa Timur');
INSERT INTO `food` VALUES (966, 'Nasi Jagung', 'Jawa Timur');
INSERT INTO `food` VALUES (967, 'Ikan Asap', 'Jawa Timur');
INSERT INTO `food` VALUES (968, 'Pelas', 'Jawa Timur');
INSERT INTO `food` VALUES (969, 'Kue Dumbek', 'Jawa Timur');
INSERT INTO `food` VALUES (970, 'Ampo', 'Jawa Timur');
INSERT INTO `food` VALUES (971, 'Keripik Pisang', 'Jawa Timur');
INSERT INTO `food` VALUES (972, 'Sale Pisang', 'Jawa Timur');
INSERT INTO `food` VALUES (973, 'Keripik Sale Pisang', 'Jawa Timur');
INSERT INTO `food` VALUES (974, 'Soto Pacitan', 'Jawa Timur');
INSERT INTO `food` VALUES (975, 'Sayur Kalakan', 'Jawa Timur');
INSERT INTO `food` VALUES (976, 'Tahu Tuna', 'Jawa Timur');
INSERT INTO `food` VALUES (977, 'Bajingan', 'Jawa Timur');
INSERT INTO `food` VALUES (978, 'Sego Berkat', 'Jawa Timur');
INSERT INTO `food` VALUES (979, 'Kolong Klitik', 'Jawa Timur');
INSERT INTO `food` VALUES (980, 'Jadah bakar', 'Jawa Timur');
INSERT INTO `food` VALUES (981, 'Betutu', 'Bali');
INSERT INTO `food` VALUES (982, 'Babi Guling', 'Bali');
INSERT INTO `food` VALUES (983, 'Bandot', 'Bali');
INSERT INTO `food` VALUES (984, 'Be Kokak Mekuah', 'Bali');
INSERT INTO `food` VALUES (985, 'Be Pasih Mesambel Matah', 'Bali');
INSERT INTO `food` VALUES (986, 'Berengkes', 'Bali');
INSERT INTO `food` VALUES (987, 'Grangasem', 'Bali');
INSERT INTO `food` VALUES (988, 'Jejeruk', 'Bali');
INSERT INTO `food` VALUES (989, 'Jukut Ares', 'Bali');
INSERT INTO `food` VALUES (990, 'Jukut Srombotan', 'Bali');
INSERT INTO `food` VALUES (991, 'Jukut Urab', 'Bali');
INSERT INTO `food` VALUES (992, 'Komoh', 'Bali');
INSERT INTO `food` VALUES (993, 'Lawar', 'Bali');
INSERT INTO `food` VALUES (994, 'Nasi Bubuh', 'Bali');
INSERT INTO `food` VALUES (995, 'Nasi Tepeng', 'Bali');
INSERT INTO `food` VALUES (996, 'Penyon', 'Bali');
INSERT INTO `food` VALUES (997, 'Sate Kakul', 'Bali');
INSERT INTO `food` VALUES (998, 'Sate Kablet', 'Bali');
INSERT INTO `food` VALUES (999, 'Sate Lilit', 'Bali');
INSERT INTO `food` VALUES (1000, 'Sate Pentul', 'Bali');
INSERT INTO `food` VALUES (1001, 'Sate Penyu', 'Bali');
INSERT INTO `food` VALUES (1002, 'Sate Tusuk', 'Bali');
INSERT INTO `food` VALUES (1003, 'Srombotan', 'Bali');
INSERT INTO `food` VALUES (1004, 'Timbungan', 'Bali');
INSERT INTO `food` VALUES (1005, 'Nasi Jenggo', 'Bali');
INSERT INTO `food` VALUES (1006, 'Tum', 'Bali');
INSERT INTO `food` VALUES (1007, 'Urutan', 'Bali');
INSERT INTO `food` VALUES (1008, 'Bubuh Sagu', 'Bali');
INSERT INTO `food` VALUES (1009, 'Bubuh Sumsum', 'Bali');
INSERT INTO `food` VALUES (1010, 'Bubuh Tuak', 'Bali');
INSERT INTO `food` VALUES (1011, 'Jaja Batun Duren', 'Bali');
INSERT INTO `food` VALUES (1012, 'Jaja Begina', 'Bali');
INSERT INTO `food` VALUES (1013, 'Jaja Bendu', 'Bali');
INSERT INTO `food` VALUES (1014, 'Jaja Bikang', 'Bali');
INSERT INTO `food` VALUES (1015, 'Jaja Engol', 'Bali');
INSERT INTO `food` VALUES (1016, 'Jaja Godoh', 'Bali');
INSERT INTO `food` VALUES (1017, 'Jaja Jongkok', 'Bali');
INSERT INTO `food` VALUES (1018, 'Jaja Ketimus', 'Bali');
INSERT INTO `food` VALUES (1019, 'Jaja Klepon', 'Bali');
INSERT INTO `food` VALUES (1020, 'Jaja Lak-Lak', 'Bali');
INSERT INTO `food` VALUES (1021, 'Jaja Sumping', 'Bali');
INSERT INTO `food` VALUES (1022, 'Jaja Tain Buati', 'Bali');
INSERT INTO `food` VALUES (1023, 'Jaja Uli misi Tape', 'Bali');
INSERT INTO `food` VALUES (1024, 'Jaja Wajik', 'Bali');
INSERT INTO `food` VALUES (1025, 'Kacang Rahayu', 'Bali');
INSERT INTO `food` VALUES (1026, 'Rujak Bulung', 'Bali');
INSERT INTO `food` VALUES (1027, 'Rujak Kuah Pindang', 'Bali');
INSERT INTO `food` VALUES (1028, 'Rujak Manis', 'Bali');
INSERT INTO `food` VALUES (1029, 'Rujak Tibah', 'Bali');
INSERT INTO `food` VALUES (1030, 'Salak Bali', 'Bali');
INSERT INTO `food` VALUES (1031, 'Range[butuh rujukan]', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1032, 'Pangaha Balu', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1033, 'Oha po\'o', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1034, 'Oha Santa', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1035, 'Tarekeli (kue delapan)', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1036, 'Pangaha Sinci', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1037, 'Pangaha Bunga', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1038, 'Birua', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1039, 'Kacipo', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1040, 'Kalempe', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1041, 'Kacantumbu', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1042, 'Kalembe', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1043, 'Sako Sako', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1044, 'Apa Puru', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1045, 'Salome', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1046, 'Sendo', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1047, 'Karedo Maci Kandole', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1048, 'Kue Bawang', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1049, 'Jinta', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1050, 'Ba\'e Neba', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1051, 'Da\'da\'', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1052, 'Ponte Kalo', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1053, 'U\'a Numpu', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1054, 'Mina sarua', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1055, 'Bingka dolu', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1056, 'Kue Lapi', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1057, 'Sri kaya', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1058, 'Jalang Kote Oi Saha', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1059, 'Mie Goreng Oi Saha', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1060, 'Kue Monto', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1061, 'Barongko', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1062, 'Palumara Kalo', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1063, 'Jago Puru', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1064, 'Jago Lowi', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1065, 'Jago Sombu', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1066, 'Karba Jago', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1067, 'Pici Kalo', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1068, 'Ayam Taliwang', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1069, 'Sate Bulayak', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1070, 'Plecing Kangkung', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1071, 'Bingka Dolu Gula Merah', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1072, 'Plecing Ayam', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1073, 'beberuk terong', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1074, 'Ares', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1075, 'Bebalung', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1076, 'Nasi Balap Puyung', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1077, 'Beberuk', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1078, 'Ayam Pelalah', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1079, 'Ebatan', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1080, 'Sate Ikan Laut Tanjung', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1081, 'Sepat Khas Sumbawa', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1082, 'Singang', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1083, 'Permen Susu Kerbau', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1084, 'Jaje Iwel', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1085, 'Temerodok', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1086, 'Jajan Bantal', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1087, 'Ayam Rarang', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1088, 'Sate Bulayak', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1089, 'Kagape Bima', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1090, 'Mangge Mada', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1091, 'Utambeca Parongge', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1092, 'Sako', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1093, 'Mangge Mada jantung pisang', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1094, 'Jame', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1095, 'Sepi', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1096, 'Doco\' mangge', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1097, 'tota fo\'o', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1098, 'Utambeca Maci', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1099, 'Uta Mbeca Saronco', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1100, 'Uta Kare', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1101, 'Uta Karamba', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1102, 'Lada', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1103, 'Uta Kato', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1104, 'Oha Jago', 'Nusa Tenggara Barat');
INSERT INTO `food` VALUES (1105, 'Lempok', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1106, 'Ale Ale', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1107, 'Bie Pang', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1108, 'Sate Manis', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1109, 'Cah Kangkung Belacan', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1110, 'Ganepuk Telur', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1111, 'Manisan Dorong', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1112, 'Pisang Goreng Pontianak', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1113, 'Kue Bingka Kentang', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1114, 'Ayam Bakar', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1115, 'Kwetiauw Siram', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1116, 'Ca Kwe', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1117, 'Tar Piring', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1118, 'Air Tahu', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1119, 'Lidah Buaya', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1120, 'Gulai Pakis', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1121, 'Nasi Tomat', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1122, 'Dangi', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1123, 'Sari Kacang Hijau', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1124, 'Bubur Pedas', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1125, 'Ikan Asam Pedas', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1126, 'Ikan Peletuk Masak Kuning', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1127, 'Ikan Pekasam', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1128, 'Sambal Popat Asam Pelam', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1129, 'Pekating', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1130, 'Tempoyak', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1131, 'Cucur', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1132, 'Lemang', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1133, 'Babi Kecap', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1134, 'Kerupuk Basah', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1135, 'Pengkang', 'Kalimantan Barat');
INSERT INTO `food` VALUES (1136, 'Amparan Tatak Pisang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1137, 'Amparan Tatak Sagu', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1138, 'Apam Barabai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1139, 'Apam Baras', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1140, 'Apam Parangge', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1141, 'Alua', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1142, 'Balungan Hayam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1143, 'Bingka Barandam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1144, 'Bubur Gunting', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1145, 'Bubur Sagu', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1146, 'Cangkarok Karing', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1147, 'Cucur', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1148, 'Dadar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1149, 'Gagatas', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1150, 'Gagati', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1151, 'Gaguduh', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1152, 'Garigit', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1153, 'Gumpal', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1154, 'HIntalu Karuang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1155, 'Ipau', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1156, 'Jagung Pipilan Bajarang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1157, 'Kikicak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1158, 'Kokoleh', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1159, 'Kue Lam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1160, 'Lakatan Bahintti', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1161, 'Laksa', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1162, 'Lalampar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1163, 'Lamang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1164, 'Lapat Lakatan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1165, 'Lapis', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1166, 'Lempeng Pisang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1167, 'Lupis', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1168, 'Pakasam Sapat', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1169, 'Patah', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1170, 'Pisang Salai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1171, 'Pupudak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1172, 'Putri Selat', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1173, 'Putu Mayang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1174, 'Putu Labu', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1175, 'Rangai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1176, 'Rangkasusun', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1177, 'Sarimuka', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1178, 'Sari Pangantin', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1179, 'Serabi', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1180, 'Slada Gumbili', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1181, 'Topi Baja', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1182, 'Ulin-ulin', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1183, 'Untuk', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1184, 'Upak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1185, 'Wadai Gayam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1186, 'Wadai Pare', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1187, 'Kalalapon', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1188, 'Bubur Habang Bubur Putih', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1189, 'Apam Barabai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1190, 'Lakatan Ba Inti', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1191, 'Dulinat', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1192, 'Sutra Ambon', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1193, 'Sarikaya', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1194, 'Kayapun/Bingka', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1195, 'Wadai Bapulas', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1196, 'Akar Pinang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1197, 'Cucur Bujang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1198, 'Wajik', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1199, 'Dodol Kandangan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1200, 'Dodol Danau Salak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1201, 'Dodol Kacang-durian', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1202, 'Bubur Bunting', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1203, 'Kukuleh', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1204, 'Rempe', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1205, 'Gagampam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1206, 'Puracit', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1207, 'Lupis', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1208, 'Wadai Kelamben', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1209, 'Wadai Tambak Anyar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1210, 'Wadai Cincin', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1211, 'Gangan Asam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1212, 'Gangan Asam Daging', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1213, 'Gangan Asam Patin', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1214, 'Gangan Gadang Pisang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1215, 'Ganngan Haliling', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1216, 'Gangan Humbut', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1217, 'Gangang Nangka', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1218, 'Gangang Rabung', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1219, 'Gangang Batang Pisang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1220, 'Gangang tongkol', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1221, 'Gangang supan supan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1222, 'Gangan Kaladi', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1223, 'Gangan Kangkung', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1224, 'Gangan Karuh', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1225, 'Gangan Ludeh Nangka', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1226, 'Gangan Luncar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1227, 'Gangan Masak Karing', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1228, 'Gangan Nangka', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1229, 'Gangan Pisang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1230, 'Gangan Rabung', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1231, 'Gangan Waluh', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1232, 'Garih Batanak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1233, 'Kalakai Batumis', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1234, 'Kambang Tigaron Bajaruk', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1235, 'Karih Daging', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1236, 'Luncar Kaladi', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1237, 'Opor Tarung', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1238, 'Tarung Babanam Basantan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1239, 'Terung Tumis', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1240, 'Using-using Hundang Papai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1241, 'Using-using Kangkung', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1242, 'Using-using Tarung', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1243, 'Ayam Masak Habang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1244, 'Biawan Baubar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1245, 'Buras', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1246, 'Hampap/Haruan Kering Batanak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1247, 'Hintalu Jaruk', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1248, 'Hintalu Masak Habang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1249, 'Jaruk Kalangkala', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1250, 'Jaruk Lumbu Kaladi Bapais', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1251, 'Jaruk Tarap', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1252, 'Katupat Kandangan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1253, 'Lampam Baubar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1254, 'Lontong', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1255, 'Mandai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1256, 'Nasi Pundut', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1257, 'Nasi Samin', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1258, 'Pada\' Basanga', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1259, 'Pakasam Sapat', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1260, 'Papuyu Baubar/Papuyu Bakar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1261, 'Papuyu Basanga', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1262, 'Saluang Basanga', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1263, 'Sambal Goreng Pakasam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1264, 'Sapat Siam Baubar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1265, 'Sate Banjar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1266, 'Hundang Papai', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1267, 'Soto Banjar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1268, 'Masak Habang', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1269, 'Masak Putih', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1270, 'Masak Kuning', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1271, 'Masak Tuha', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1272, 'Katupat Kandangan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1273, 'Laksa', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1274, 'Lontong', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1275, 'Papuyu Baubar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1276, 'Haruan/tauman baubar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1277, 'sapat siam baubar', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1278, 'paisan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1279, 'Samu ikan-tarap-tiwadak', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1280, 'Masak Kicap', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1281, 'Masak asam', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1282, 'Pangatan', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1283, 'Wadi', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1284, 'Garih', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1285, 'Urap', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1286, 'Nasi itik Gambut', 'Kalimantan Selatan');
INSERT INTO `food` VALUES (1287, NULL, NULL);
INSERT INTO `food` VALUES (1288, NULL, NULL);
INSERT INTO `food` VALUES (1289, NULL, NULL);
INSERT INTO `food` VALUES (1290, NULL, NULL);
INSERT INTO `food` VALUES (1291, NULL, NULL);
INSERT INTO `food` VALUES (1292, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
